test_array=[
['être', 'to be; being']
,['avoir', 'to have']
,['je', 'I']
,['de', 'of, from, by, than, in, with']
,['ne', 'not']
,['pas', 'not; step, pace']
,['le', 'the; him, it (refering to a masculine singular noun)']
,['la', 'the; her, it (refering to a feminine singular noun)']
,['tu', 'you']
,['vous', 'you, yourself']
,['il', 'he, it']
,['et', 'and']
,['à', 'in, to, with']
,['un', 'a, an; one (used before a masculine singular noun)']
,["l'", "the (used instead of 'le' or 'la' before nouns that begin with a vowel)"]
,['qui', 'who, whom; that, which']
,['aller', 'to go']
,['les', 'the; them (referring to a plural noun)']
,['en', 'in, into, to, as']
,['ça', 'this, that']
,['faire', 'to do, make']
,['tout', 'all, everything, any; very, quite']
,['on', 'we, you']
,['que', 'that; what; which']
,['ce', 'this, that']
,['une', 'a, an; one (used before a feminine singular noun)']
,['mes', 'my (used before plural nouns)']
,["d'", "of, from, by, than, in, with (used before a vowel or mute h)"]
,['pour', 'for']
,['se', 'himself, herself, themselves']
,['des', 'some (used before a plural noun)']
,['dire', 'to say, tell']
,['pouvoir', 'can, to be able to']
,['vouloir', 'to want']
,['mais', 'but']
,['me', 'me, myself']
,['nous', 'we, us']
,['dans', 'in, into']
,['elle', 'she, it (refers to a feminine singular noun)']
,['savoir', 'to know']
,['du', '(de + le/les) = of the, from the']
,['où', 'where, that']
,['y', 'it, there']
,["t'", "you, yourself (shortened form used before a vowel)"]
,['bien', 'well, very; good']
,['voir', 'to see']
,['plus', 'more']
,['non', 'no']
,['te', 'you, yourself']
,['mon', 'my (used before a masculine singular noun)']
,['au', 'at the, to the, in the (contraction of à + le; used with a singular masculine noun)']
,['avec', 'with']
,['moi', 'I, me']
,['si', 'yes; if; so, such']
,['quoi', 'what (exclamatory, interrogative, after preposition)']
,['devoir', 'to have to, must; duty, test']
,['oui', 'yes']
,['ils', 'they (refers to a group of masculine or mixed masculine/feminine nouns)']
,['comme', 'as, like; how, same']
,["s'", "himself, herself, themselves (variation of 'se' used before a word starting with a vowel or mute h)"]
,['venir', 'to come, occur']
,['sur', 'on, upon; over (preposition); sour (adjective)']
,['toi', 'you']
,['ici', 'here']
,['rien', 'nothing']
,['lui', 'he, him, it, her']
,['bon', 'good, right, kind; good!; voucher; then;']
,['là', 'there, here, then']
,['suivre', 'to follow']
,['pourquoi', 'why']
,['parler', 'to speak, talk']
,['prendre', 'to take, get']
,['cette', 'this, that (feminine singular)']
,['quand', 'when, whenever']
,['alors', 'then; so; hence']
,['une chose', 'thing, matter']
,['par', 'per, by, through, out of']
,['son', 'his, her, its (possessive adjective); sound (noun - le son)']
,['croire', 'to believe, think']
,['aimer', 'to love, like, be fond of']
,['falloir', 'it is necessary, must, have to']
,['comment', 'how; what']
,['très', 'very']
,['ou', 'or; either… or']
,['passer', 'to pass, go by, cross']
,['penser', 'to think']
,['aussi', 'also, too']
,['jamais', 'never']
,['attendre', 'to wait for, expect']
,['trouver', 'to find']
,['laisser', 'to leave']
,['petit', 'small, little, young (adjective); kid, child (masculine noun)']
,['merci', 'thanks, thank you']
,['même', 'same; even, so much as, as']
,['sa', 'his, her, its (feminine)']
,['ta', 'your (reminine)']
,['autre', 'other, another, different (singular)']
,['arriver', 'to arrive']
,['ces', 'these, those (plural form of masculine "ce" and feminine "cette")']
,['donner', 'to give, give away']
,['regarder', 'to look at, watch']
,['encore', 'again, over again, even, still']
,['appeler', 'to call, ring']
,['est-ce que', 'is it']
,['peu', 'not much, not very, few; bit']
,['homme', 'man']
,['partir', 'to go, leave, go away']
,['ma', 'my (used before a feminine singular noun)']
,['toujours', 'always, still']
,['jour', 'day, daytime']
,['femme', 'woman, wife']
,['temps', 'weather; time; times']
,['maintenant', 'now, nowadays']
,['notre', 'our (singular)']
,['vie', 'life, lifetime, existence']
,['deux', 'two']
,['mettre', 'to put, put on, wear']
,['rester', 'to stay, remain']
,['sans', 'without']
,['seul', 'alone']
,['arrêter', 'to stop']
,['vraiment', 'really, truly']
,['connaître', 'to know, experience']
,['quelque', 'some, a few, any']
,['sûr', 'on, over']
,['tuer', 'to kill']
,['mourir', 'to die, pass away']
,['demander', 'to ask, ask for, be looking for']
,['juste', 'just, fair; just, right, accurate']
,['peut-être', 'perhaps, maybe']
,['dieu', 'god']
,['fois', 'time']
,['oh', 'oh!']
,['père', 'father']
,['comprendre', 'to understand']
,['sortir', 'to go out; take out']
,['personne', 'anyone, anybody; person, individual']
,['an', 'year']
,['trop', 'too much, too (excessively)']
,['chez', 'at, to, in']
,['fille', 'daughter, girl']
,['aux', '(à + les) = of the']
,['monde', 'world, people']
,['ami', 'friend; friendly']
,['vrai', 'true, real, genuine']
,['après', 'after, afterwards, later']
,['mal', 'trouble, difficulty; badly, wrongly']
,['besoin', 'need, demand, necessity']
,['accord', 'agreement, accord, harmony']
,['ses', 'his, her, its (plural)']
,['avant', 'before']
,['monsieur', 'gentleman, Mr']
,['enfant', 'child, infant']
,['grand', 'big, large, tall, great; big boy, big girl']
,['entendre', 'to hear, listen to, understand']
,['voilà', 'there is, there are']
,['chercher', 'to look for, seek']
,['heure', 'hour; time; age']
,['mieux', 'better, utmost, best; improvement']
,['tes', 'your (plural)']
,['aider', 'to help, aid']
,['mère', 'mother']
,['déjà', 'already, before']
,['beau', 'beautiful, lovely, pretty; fine, nice (weather)']
,['essayer', 'to come back, return']
,['donc', 'so, therefore']
,['plaire', 'to be successful']
,['maison', 'house, home']
,['gens', 'people (plural)']
,['nuit', 'night']
,['ah', 'ah!']
,['soir', 'evening, night']
,['nom', 'name; noun']
,['bonjour', 'hello']
,['jouer', 'to play']
,['leur', 'their, to them (mas or fem), theirs (masc, fem, plural)']
,['finir', 'to finish, end']
,['peur', 'fear, fright']
,['mort', 'death; dead']
,['parce que', 'because, for']
,['perdre', 'to lose, miss']
,['maman', 'mommy']
,['sentir', 'to smell, sniff, feel']
,['ouais', 'yeah, yep']
,['rentrer', 'to bring in, take in; to get in, go in, come home']
,['nos', 'our (plural)']
,['premier', 'first, basic; first floor']
,['problème', 'problem']
,['argent', 'silver, money']
,['quelle', 'who, what, which']
,['vivre', 'to live, be alive, go through']
,['rendre', 'to return, give back, repay']
,['dernier', 'last, latest']
,['tenir', 'to hold, run, keep, last']
,['cet', 'this, that (before vowel and mute h)']
,['main', 'hand']
,['cela', 'this, that (used in formal contexts and expressions)']
,['vite', 'quickly, fast, soon']
,['oublier', 'to forget, miss']
,['air', 'air; look, appearance, manner']
,['salut', 'greeting; Hi!, Hello!, Bye!']
,['fils', 'son']
,['travailler', 'to work, work on, practise']
,['moins', 'less']
,['tête', 'head, face']
,['coup', 'blow, shot, kick, punch']
,['écouter', 'to listen to']
,['raison', 'reason']
,['manger', 'to eat']
,['amour', 'love, cupid']
,['entrer', 'to go in, enter, come in']
,['dont', 'whose, of which']
,['nouveau', 'new, fresh']
,['devenir', 'to become']
,['hein', 'what?, eh?, Huh? (familiar)']
,['commencer', 'to start, begin']
,['moment', 'moment, while, point']
,['voiture', 'car, coach, carriage']
,['vieux', 'old; old man, old woman']
,['demain', 'tomorrow']
,['revoir', 'to see again, review; goodbye']
,['elles', 'they (refers to a group of feminine nouns or females)']
,['payer', 'to pay']
,['fou', 'mad, crazy; madman, fool']
,['tirer', 'to pull, draw']
,['ouvrir', 'to open']
,['oeil', 'eye, view (= œil) (plural is yeux)']
,['fait', 'event, fact']
,['changer', 'to change, exchange']
,['question', 'question, matter']
,['tomber', 'to fall']
,['assez', 'enough, quite, fairly']
,['excuser', 'to forgive, pardon, excuse']
,['affaire', 'affiar, business']
,['dormir', 'to sleep; to lie idle']
,['combien', 'how much, how many']
,['frère', 'brother']
,['travail', 'work, labor, employment']
,['idée', 'idea, opinion']
,['eh', 'hey!']
,['puis', 'next, then, besides, plus (in addition)']
,['famille', 'family']
,['truc', 'trick, knack, thing']
,['trois', 'three']
,['tant', 'much, so much']
,['souvenir', 'memory, souvenir; to remember']
,['ni', 'nor, or (negative)']
,['tous', 'everything, all (plural)']
,['occuper', 'to occupy, live in, take up']
,['entre', 'between, among']
,['ok', 'OK; okay (satisfactory)']
,['marcher', 'to walk, march, go']
,['chance', 'luck, fortune, chance']
,["aujourd'hui", 'today, nowadays']
,['envoyer', 'to send, throw, dispatch, refer']
,['histoire', 'history, story']
,['jeune', 'young, youthful; young person']
,['tard', 'late']
,['apprendre', 'to learn, to hear (about)']
,['minute', 'minute']
,['boire', 'to drink, to soak up']
,['garder', 'to keep, to look after, to guard']
,['quelques', 'some (quantity), small number, a few']
,['type', 'type, kind; guy (colloquial)']
,['porte', 'gate, door']
,['montrer', 'to show, point out']
,['mec', 'guy, bloke']
,['asseoir', 'to sit down, sit up']
,['porter', 'to carry, wear']
,['attention', 'attention']
,['année', 'year']
,['sous', 'under']
,['prêt', 'ready']
,['contre', 'against']
,['prier', 'to pray']
,['pendant', 'for, during']
,['mois', 'month']
,['meilleur', 'better; the best one']
,['servir', 'to serve']
,['madame', 'madam, Mrs']
,['écrire', 'to write']
,['part', 'part, share']
,['eau', 'water']
,['sang', 'blood']
,['place', 'room, square, seat']
,['espérer', 'to hope for']
,['plein', 'full, solid']
,['désoler', 'to distress, upset']
,['eux', 'them, they']
,['retrouver', 'to find; to meet']
,['ville', 'town, city']
,['terre', 'earth, ground']
,['gagner', 'to win, earn']
,['semaine', 'week']
,['acheter', 'to buy']
,['longtemps', 'long, for a long time']
,['gars', 'boy, chap, guy']
,['chambre', 'bedroom, chamber']
,['hé', 'Hey! (to attract attention)']
,['côté', 'coast, slope, side']
,['droit', 'law, right; straight']
,['rappeler', 'to remind, remember, call back, be reminiscent of']
,['lire', 'to read']
,['cas', 'case, instance']
,['mot', 'word']
,['seulement', 'only, solely']
,['voici', 'here is, here are']
,['monter', 'to go up, rise, come up']
,['désolé', 'contrite, desolate, afraid, sorry']
,['quitter', 'to leave, depart']
,['police', 'police']
,['suite', 'rest, result']
,['matin', 'morning']
,['emmener', 'to take (somebody), take along']
,['toucher', 'to touch']
,['continuer', 'to continue, go on']
,['devant', 'in front, ahead; in front of, ahead of, past, before']
,['fort', 'strong, solid; loud, much, most']
,['gros', 'big, large, thick, heavy']
,['enfin', 'finally, at last']
,['pardon', "I'm sorry!, Excuse me!, Pardon?; forgiveness"]
,['mari', 'husband']
,['là-bas', 'there, over there']
,['importer', 'to import; to matter']
,['papa', 'daddy, dad']
,['train', 'train, pace']
,['manquer', 'to miss, to miss somebody']
,['raconter', 'to tell']
,['ensemble', 'together, at once']
,['mauvais', 'bad, poor, wrong']
,['film', 'film, movie']
,['répondre', 'to answer, reply']
,['garçon', 'boy, chap, guy']
,['corps', 'body']
,['celui', 'the one, that one (singular masculine) ']
,['autres', 'other']
,['heureux', 'happy, felicitous']
,['loin', 'far, a long way off, a long time ago']
,['aucun', 'no, not any; none']
,['pauvre', 'poor; poor person, beggar']
,['sauver', 'to save']
,['chaque', 'each, every']
,['retourner', 'to turn, turn over, return']
,['leurs', 'theirs (3rd person masculine or feminine plural)']
,['rencontrer', 'to meet, encounter']
,['coeur', 'core, heart']
,['voler', 'to flly; to steal, swipe']
,['fermer', 'to close, shut']
,['car', 'because, for']
,['valoir', 'to hold, apply; to be worth']
,['descendre', 'to take down, go down, come down']
,['feu', 'fire']
,['docteur', 'doctor, physician']
,['suffire', 'to be enough, suffice']
,['façon', 'way, manner, behaviour']
,['important', 'important, considerable, sizeable']
,['sembler', 'to seem, appear, look']
,['super', 'great, fantastic; high-octane gasoline']
,['compter', 'to count']
,['vers', 'towards, near, around, about (time, age)']
,['joli', 'nice, tidy, pretty (attractive), lovely (beautiful)']
,['point', 'dot, full stop, period']
,['noir', 'black']
,['hier', 'yesterday']
,['chien', 'dog']
,['guerre', 'war']
,['genre', 'kind, type, sort']
,['marier', 'to marry, get married']
,['arme', 'weapon']
,['cause', 'cause, reason']
,['endroit', 'place']
,['ordre', 'order, command']
,['poser', 'to put down, lay, pose, sit']
,['reste', 'the remainder, rest']
,['pied', 'foot; stem, leg, base']
,['près', 'near']
,['fin', 'end, ending']
,['tiens', 'Why!, Hello! (surprise)']
,['inquiéter', 'to worry, bother, trouble']
,["d'autres", 'others; more']
,['bouger', 'to move']
,['plutôt', 'rather, quite']
,['apporter', 'to bring, supply']
,['photo', 'photo, photography']
,['décider', 'to decide']
,['ainsi', 'like this, in this way']
,['certain', 'certain, sure']
,['aucune', 'no, not any, in no way']
,['vendre', 'to sell']
,['école', 'school']
,['cher', 'dear, beloved, darling, expensive']
,['chef', 'leader, chief, head']
,['tourner', 'to turn, stir, toss, shoot']
,['cacher', 'to hide, conceal']
,['boulot', 'work, job']
,['pays', 'country, nation, land (country)']
,['ceux', 'this one, that one (masculine plural)']
,['possible', 'possbile']
,['expliquer', 'to explain, account for']
,['battre', 'to beat']
,['peine', 'sorrow, grief, saddness, suffering']
,['livre', 'book; pound']
,['agir', 'to act, behave; work, take effect']
,['imaginer', 'to imagine, suppose']
,['tour', 'tower, castle, tour, ballot']
,['adorer', 'to adore, love']
,['vérité', 'truth']
,['recevoir', 'to receive, to get']
,['gentil', 'kind, good, nice']
,['jeter', 'to throw']
,['pleurer', 'verb']
,['bébé', 'baby']
,['partie', 'part; game']
,['nouvelle', 'new, fresh']
,['jeu', 'play, game; hand, deck (cards)']
,['amener', 'to bring, take, bring about']
,['instant', 'instant, moment']
,['parent', 'relative, relation; parent']
,['dur', 'hard, tough, harsh']
,['service', 'service, favor']
,['promettre', 'to promise']
,['mentir', 'to lie']
,['soeur (sœur)', 'sister']
,['bientôt', 'soon, quickly, shortly']
,['lit', 'bed']
,['tellement', 'so (to such an extent), so (very), so much']
,['utiliser', 'to use']
,['lieu', 'place, site']
,['coucher', 'to put to bed, lay down, to sleep']
,['presque', 'almost, nearly']
,['dehors', 'outside, outdoors']
,['passé', 'past, last; the past, past tense']
,['préférer', 'to prefer']
,['content', 'happy, pleased, glad']
,['derrière', 'behind']
,['offrir', 'to offer, give']
,['roi', 'king']
,['verre', 'glass, drink']
,['réveiller', 'to awake, wake (smb.) up']
,['aide', 'assistant; help, assistance']
,["d'abord", 'foremost (most important), first']
,['journée', 'day']
,['préparer', 'to prepare, make, get ready']
,['numéro', 'number']
,['permettre', 'to allow, permit']
,['ramener', 'to bring back , take back']
,['enlever', 'to take (smth.) away, remove, take off']
,['calme', 'peace, calmness; quiet, calm']
,['lâcher', 'to let go of, to release']
,['choisir', 'to choose']
,['musique', 'music']
,['conduire', 'to drive, lead']
,['faute', 'mistake, error; fault; lack of']
,['calmer', 'to calm down, appease, sooth']
,['dîner', 'dinner; to have dinner']
,['mariage', 'marriage, wedding']
,['bureau', 'writing desk, study (room), office']
,['route', 'road, journey, way']
,['chanter', 'to sing']
,['secret', 'secret; secretive']
,['disparaître', 'to disappear, vanish']
,['lever', 'to raise, lift']
,['dessus', 'on top; top']
,['présenter', 'to introduce, present']
,['accepter', 'to accept']
,['sinon', 'otherwise, or else, except']
,['long', 'long, lengthy']
,['café', 'coffee, café (bar)']
,['propre', 'clean, tidy']
,['confiance', 'trust, confidence, belief']
,['cinq', 'five']
,['bonsoir', 'good evening, good night']
,['compte', 'count, number']
,['téléphone', 'telephone, phone']
,['casser', 'to break, shatter']
,['prochain', 'next']
,['facile', 'easy']
,['rêve', 'dream']
,['copain', 'friend, boyfriend']
,['malade', 'ill, sick']
,['rue', 'street']
,['bas', 'low; bottom']
,['lettre', 'letter']
,['ignorer', 'not to know, to ignore']
,['fête', 'party, celebration']
,['couper', 'to cut, cut off']
,['esprit', 'mind, brain, wit, spirit, esprit']
,['taire', 'to be silent, stop talking']
,['flic', 'cop, policeman']
,['parfois', 'sometimes']
,['capitaine', 'captain']
,['âge', 'age']
,['autant', 'so much, so many']
,['force', 'force, strength']
,['pièce', 'room; play; coin; piece']
,['quatre', 'four']
,['difficile', 'difficult, strenuous, hard']
,['bras', 'arm']
,['tromper', 'to deceive; to make a mistake']
,['surtout', 'above all']
,['ressembler', 'to look like, to resemble']
,['plan', 'map, plan, layout']
,['sale', 'dirty']
,['courir', 'to run, rush']
,['haut', 'high, elevated; top']
,['état', 'state']
,['remettre', 'to put back; hand over; postpone; put back on']
,['carte', 'map, card']
,['paix', 'peace, calmness; quiet, calm']
,['exactement', 'exactly, accurately, precisely']
,['drôle', 'funny, peculiar']
,['refuser', 'to refuse, turn down']
,['dès', 'from']
,['président', 'president, chairman']
,['cours', 'class, course']
,['grave', 'serious, grave, solemn']
,['terminer', 'to end, finish']
,['ciel', 'sky']
,['partout', 'everywhere']
,['âme', 'soul']
,['patron', 'boss, manager, owner']
,['amuser', 'to amuse, entertain']
,['celle', 'the one, that one (feminine singular)']
,['visage', 'face']
,['intéresser', 'to interest']
,['reconnaître', 'to recognize, acknowledge']
,['rire', 'to laugh, have fun, joke']
,['médecin', 'doctor, physician, medical practitioner']
,['rapport', 'report, connection, link, relationship']
,['pardonner', 'to forgive, pardon, excuse']
,['avis', 'opinion; notice']
,['retour', 'return']
,['laquelle', 'which one = (le + quelle) (feminine singular)'               ]
,['simple', 'simple']
,['danser', 'to dance']
,['exister', 'to exist']
,['différent', 'different, various, other']
,['souvent', 'often']
,['lumière', 'light']
,['génial', 'great, brilliant']
,['libre', 'free, vacant']
,['dollar', 'dollar']
,['sûrement', 'surely, certainly, most probably']
,['pareil', 'the same']
,['hôpital', 'hospital']
,['ceci', 'this (formal contexts; refers to nouns that have no specific gender) (see #20, 203)']
,['réussir', 'to be successful, succeed']
,['bizarre', 'odd, starnge, bizarre']
,['voix', 'voice']
,['protéger', 'to protect']
,['honneur', 'honor (US), honour']
,['tôt', 'early']
,['équipe', 'team, crew, party']
,['prévenir', 'to tell, inform, prevent']
,['cheval', 'horse']
,['ailleurs', 'elsewhere, somewhere else']
,['lequel', 'which one = (le + quel) (masculine singular)']
,['maître', 'master, ruler, mistress, school teacher']
,['avion', 'plane']
,['bout', 'bit, tip, end']
,['habiter', 'to live in']
,['faim', 'hunger']
,['ensuite', 'then, next, afterwards']
,["l'un", "a, an, one (replaces 'un' when 'un' is a pronoun or at the beginning of a sentence) (see #14)"]
,['froid', 'cold']
,['normal', 'normal, usual']
,['déranger', 'to disturb, upset']
,['reprendre', 'to recapture, take back']
,['oncle', 'uncle']
,['prix', 'price; prize']
,['retard', 'delay, lateness']
,['détruire', 'to destroy, ruin']
,['cadeau', 'present, gift']
,['pousser', 'to push, press']
,['face', 'face; heads']
,['gueule', 'mouth']
,['chemin', 'path, way']
,['vivant', 'vibrant, living, alive']
,['général', 'general (military)']
,['bateau', 'boat, ship']
,['million', 'million']
,['sac', 'bag, sack']
,['impossible', 'impossible']
,['seconde', 'second, moment']
,['découvrir', 'to discover, find']
,['erreur', 'error, mistake']
,['soleil', 'sun, sunlight']
,['voyage', 'trip, journey']
,['sauter', 'to jump']
,['rêver', 'to dream']
,['détester', 'to hate, detest']
,['clair', 'clear, apparent']
,['faux', 'wrong, false, fallacious']
,['paraître', 'to come out, be published']
,['balle', 'ball (sports equipment)']
,['empêcher', 'to prevent']
,['maintenir', 'to keep, maintain']
,['cheveu', 'a hair']
,['papier', 'paper']
,['présent', 'a present; present, current']
,['sujet', 'subject, topic, theme']
,['supposer', 'to suppose, assume']
,['tranquille', 'quiet, calm']
,['neuf', 'nine; new, unused']
,['épouser', 'to marry, to espouse']
,['blanc', 'white; blank']
,['table', 'table']
,['toute', 'everything, all']
,['dix', 'ten, tenth']
,['clé', 'key; solutioin']
,['agent', 'officer, oficial, agent']
,['approcher', 'to approach']
,['sens', 'direction, way; meaning; sense; senses']
,['craindre', 'to fear, to be afraid of']
,['six', 'six']
,['message', 'message']
,['crier', 'to shout']
,['salle', 'room, hall, audience']
,['inviter', 'to invite']
,['effet', 'effect, impression']
,['réfléchir', 'to reflect, think']
,['espèce', 'species, kind']
,['arranger', 'to arrange, to organize']
,['naître', 'to be born']
,['allô', 'Hello! (telephone)']
,['bois', 'wood; antlers']
,['propos', 'subject, topic, remark, point']
,['camp', 'camp']
,['sorte', 'sort, kind']
,['hôtel', 'hotel']
,['début', 'beginning']
,['souffrir', 'to be in pain, suffer']
,['jambe', 'leg']
,['remercier', 'to thank']
,['choix', 'choice, selection']
,['sécurité', 'safety, security']
,['avocat', 'lawyer']
,['attraper', 'to catch']
,['client', 'customer, client, guest']
,['courant', 'current, trend']
,['dépêcher', 'to dispatch']
,['peuple', 'people']
,['dame', 'lady, queen']
,['vérifier', 'to check, verify']
,['abandonner', 'to abandon, leave, desert']
,['journal', 'newspaper, diary, journal']
,['sérieux', 'genuine, serious']
,['brûler', 'to burn']
,['or', 'gold']
,['loi', 'law, rule']
,['fond', 'bottom, back']
,['gosse', 'kid (colloquial, child, youngster)']
,['fric', 'doug, money, cash']
,['situation', 'situation; job; location']
,['euh', 'Er…']
,['sauf', 'except']
,['accident', 'accident']
,['doute', 'doubt']
,['scène', 'scene']
,['soldat', 'soldier']
,['amoureux', 'loving']
,['assurer', 'to assure, insure']
,['preuve', 'proof, evidence']
,['humain', 'human']
,['mer', 'sea, seaside']
,['silence', 'silence']
,['télé', 'TV, telly']
,['victime', 'victim, casualty']
,['complètement', 'completely, fully, in depth']
,['garde', 'guard; carer, nurse']
,['meurtre', 'murder']
,['groupe', 'group']
,['crime', 'crime']
,['traiter', 'to treat; to deal']
,['doucement', 'gently, softly']
,['blesser', 'to injure, wound, hurt']
,['colonel', 'colonel']
,['parole', 'speech, word']
,['triste', 'sad']
,['honte', 'shame']
,['rouge', 'red']
,['dégager', 'to free; to clear; to radiate']
,['soirée', 'evening, party']
,['dangereux', 'dangerous']
,['armée', 'army']
,['filer', 'to spin; to take off; to go off, to leave']
,['risquer', 'to risk']
,['dos', 'back, spine']
,['appel', 'call, appeal']
,['visite', 'visit']
,['mener', 'to take; to lead, guide, manage']
,['fleur', 'flower, blossom']
,['attaquer', 'to attack']
,['coin', 'corner, spot']
,['prince', 'prince']
,['pire', 'worse']
,['professeur', 'teacher, professor']
,['répéter', 'to repeat; to go over, rehearse']
,['habitude', 'habit, practice']
,['signer', 'to sign']
,['ficher', 'to file, put on file']
,['mériter', 'to deserve, be worth']
,['réponse', 'response, answer, reply']
,['rejoindre', 'to meet up; to join, rejoin; to go back to']
,['discuter', 'to question, dispute']
,['village', 'village']
,['pourtant', 'yet']
,['avancer', 'to move forward, advance']
,['connerie', 'stupidity']
,['reposer', 'to rest, to have a rest']
,['échapper', 'to escape, get away, slip, run away']
,['forme', 'form, shape']
,['bruit', 'noise, sound; rumour']
,['chacun', 'each, everyone']
,['diable', 'devil']
,['exemple', 'example']
,['charger', 'to charge, load']
,['chat', 'cat']
,['ennemi', 'enemy']
,['gamin', 'kid, child']
,['rendez-vous', 'appointment']
,['debout', 'standing, standing up']
,['obliger', 'to oblige']
,['trou', 'hole, gap, deficit']
,['accompagner', 'to go with, accompany']
,['fenêtre', 'window']
,['oser', 'to dare']
,['impression', 'impression']
,['intérieur', 'inside (inner surface), interrior']
,['bouche', 'mouth']
,['ligne', 'line, course, service']
,['absolument', 'absolutely']
,['doux', 'soft, mild, gentle']
];