german_array=[
['Seite, f', 'page']
,['Schmerz, m', 'pain']
,['Gemälde, n', 'painting']
,['Paar, n', 'pair']
,['Bleich', 'pale']
,['Papier, n', 'paper']
,['Eltern, pl', 'parents']
,['Park, m', 'park']
,['Parkieren', 'parking']
,['Teil, m', 'part']
,['Besonders', 'particular']
,['teilweise', 'partly']
,['Party, f', 'party']
,['Pass, m', 'passport']
,['Vergangenheit, f', 'past']
,['geduldig', 'patient']
,['Muster, n', 'pattern']
,['zahlen', 'pay']
,['Zahlung, f', 'payment']
,['Erbe, f', 'pea']
,['Frieden, m', 'peace']
,['Birne, f', 'pear']
,['Kugelschreiber, m', 'pen']
,['Leute, pl', 'people']
,['Leistung,Vorstellung, f', 'performance']
,['vielleicht', 'perhaps']
,['Punkt(Zeichen), m', 'period']
,['erlauben', 'permit']
,['Person, f', 'person']
,['persönlich', 'personal']
,['pflücken', 'pick']
,['Bild, n', 'picture']
,['Stück, n', 'piece']
,['Schwein, n', 'pig']
,['blaßrot', 'pink']
,['Ort, m, Stelle, f', 'place, spot']
,['Plan, m', 'plan']
,['Pflanze, f', 'plant']
,['Teller, m', 'plate']
,['spielen', 'play']
,['angenehm', 'pleasant']
,['bitte', 'please']
,['Vergnügen, n', 'pleasure']
,['sehr viel', 'plenty']
,['Punkt, m', 'point']
,['Polizei, f', 'police']
,['Schwimmbecken, n', 'pool']
,['arm', 'poor']
,['beliebt', 'popular']
,['Bevölkerung, f', 'population']
,['Schweinefleisch, n', 'pork']
,['Teil, m', 'portion']
,['Lage, f', 'position']
,['möglich', 'possible']
,['Postbüro, n', 'post office']
,['Postkarte, f', 'postcard']
,['Topf, m', 'pot']
,['Kartoffel, f', 'potato']
,['Macht, f,Kraft, f', 'power']
,['mächtig', 'powerful']
,['Uebung, f', 'practice']
,['beten, bitten', 'pray']
,['vorbereiten', 'prepare']
,['Geschenk, n', 'present']
,['Präsident, m', 'president']
,['Druck, m', 'pressure']
,['hübsch', 'pretty']
,['vorbeugen', 'prevent']
,['vorheriger,-e,-es', 'previous']
,['Preis, m', 'price']
,['wahrscheinlich', 'probably']
,['Problem, n', 'problem']
,['Produkt, n', 'product']
,['Programm, n', 'program']
,['Fortschritt, m', 'progress']
,['versprechen', 'promise']
,['Eigentum, n', 'property']
,['Vorschlag', 'proposal']
,['vorschlagen', 'propose']
,['Schutz, m', 'protection']
,['stolz', 'proud']
,['beweisen', 'prove']
,['liefern', 'provide']
,['Zwetschge, f', 'prune']
,['', ' ']
,['', '']
,['', 'public']
,['', 'publish']
,['', 'pull']
,['', 'pure']
,['', 'purple']
,['', 'purpose']
,['', 'push']
,['', 'put']
,['', 'quality']
,['', 'queen']
,['', 'question']
,['', 'quickly']
,['', 'quiet']
,['', 'quite']
,['', 'rabbit']
,['', 'race']
,['', 'radio']
,['', 'railroad']
,['', 'rain']
,['', 'rain (verb)']
,['', 'raise']
,['', 'range']
,['', 'rapidly']
,['', 'rare']
,['', 'rate']
,['', 'rather']
,['', 'raw']
,['', 'reach, manage']
,['', 'read']
,['', 'ready']
,['', 'real']
,['', 'reality']
,['', 'realize']
,['', 'really']
,['', 'rear']
,['', 'reason']
,['', 'reasonable']
,['', 'receive']
,['', 'recently']
,['', 'recognize']
,['', 'record']
,['', 'recover']
,['', 'red']
,['', 'reduce']
,['', 'refrigerator']
,['', 'refuse']
,['', 'regard']
,['', 'region']
,['', 'regular']
,['', 'relation']
,['', 'relatively']
,['', 'relief']
,['', 'religion']
,['', 'remain']
,['', 'remark']
,['', 'remember']
,['', 'remove']
,['', 'repeat']
,['', 'reply']
,['', 'report']
,['', 'represent']
,['', 'require']
,['', 'research (do ~)']
,['', 'research (noun)']
,['', 'responsible']
,['', 'rest']
,['', 'restaurant']
,['', 'result']
,['', 'return']
,['', 'rice']
,['', 'rich']
,['', 'right (direction)']
,['', 'right (fair)']
,['', 'right (noun)']
,['', 'ring']
,['', 'rise']
,['', 'risk']
,['', 'river']
,['', 'road']
,['', 'rock']
,['', 'role']
,['', 'roof']
,['', 'room']
,['', 'round']
,['', 'rule']
,['', 'run']
,['', ' ']
,['traurig', 'sad']
,['sicher', 'safe']
,['Salat, m', 'salad']
,['Salz, n', 'salt']
,['gleicher,-e,-es', 'same']
,['Probe, f', 'sample']
,['zufrieden', 'satisfied']
,['Samstag, m', 'Saturday']
,['Wurst, f', 'sausage']
,['retten, sichern', 'save']
,['sagen', 'say']
,['kaum', 'scarcely']
,['Szene', 'scene']
,['Schule, f', 'school']
,['Wissenschaft, f', 'science']
,['Schere, f', 'scissors']
,['Schraube, f', 'screw']
,['Meer, n', 'sea']
,['suchen', 'search']
,['Jahreszeit, f', 'season']
,['Sitz, m', 'seat']
,['zweiter,-e,-es', 'second']
,['Geheimnis, n', 'secret']
,['Sekretärin, f', 'secretary']
,['sehen', 'see']
,['suchen', 'seek']
,['scheinen', 'seem']
,['selten', 'seldom']
,['auswählen', 'select']
,['verkaufen', 'sell']
,['senden, schicken', 'send']
,['Sinn, m, Gefühl, n', 'sense']
,['September, m', 'September']
,['ernsthaft', 'serious']
,['dienen als', 'serve as']
,['Dienst, m', 'service']
,['abgemacht', 'settled']
,['sieben', 'seven']
,['siebzehn', 'seventeen']
,['siebzig', 'seventy']
,['mehrere', 'several']
,['', '']
,['', '']
,['Schatten, m', 'shadow']
,['sollen', 'shall']
,['Form, f', 'shape']
,['teilen', 'share']
,['scharf', 'sharp']
,['sich rasieren', 'shave']
,['sie', 'she']
,['Schaf, n', 'sheep']
,['Obdach, n', 'shelter']
,['Schiff, n', 'ship']
,['Hemd, n', 'shirt']
,['Schuhe, pl', 'shoes']
,['schiessen', 'shoot']
,['Laden, m', 'shop']
,['Strand, m', 'shore']
,['kurz', 'short']
,['Schuss', 'shot']
,['Schulter, f', 'shoulder']
,['zeigen', 'show']
,['krank', 'sick, ill']
,['Seite, f', 'side']
,['Zeichen, n', 'sign (noun)']
,['unterschreiben', 'sign (verb)']
,['Signal, n', 'signal']
,['bedeuten', 'signify']
,['Ruhe, f', 'silence']
,['Silber, n', 'silver']
,['gleich', 'similar']
,['einfach', 'simple']
,['Sünde, f', 'sin']
,['seit', 'since']
,['singen', 'sing']
,['Schwester, f', 'sister']
,['sich setzen', 'sit']
,['Lage, f', 'situation']
,['sechs', 'six']
,['sechzehn', 'sixteen']
,['sechzig', 'sixty']
,['Grösse, f', 'size']
,['Haut, f', 'skin']
,['Rock, m', 'skirt']
,['Himmel, m', 'sky']
,['schlafen', 'sleep']
,['geringfügig', 'slight']
,['langsam', 'slow']
,['klein', 'small']
,['riechen', 'smell']
,['lächeln', 'smile']
,['Schmied, m', 'smith']
,['rauchen', 'smoke']
,['weich, glatt', 'smooth']
,['Schnecke, f', 'snail']
,['Schlange, f', 'snake']
,['Schnee, m', 'snow']
,['so', 'so']
,['Seife, f', 'soap']
,['Gesellschaft, f', 'society']
,['weich', 'soft']
,['Boden(Erde), m', 'soil']
,['Soldat, m', 'soldier']
,['fest', 'solid']
,['Lösung, f', 'solution']
,['einige', 'some (object)']
,['jemand', 'somebody']
,['jemand', 'someone']
,['manchmal', 'sometimes']
,['irgendwo', 'somewhere']
,['Sohn, m', 'son']
,['Lied, n', 'song']
,['bald', 'soon']
,['Klang, m', 'sound']
,['Suppe, f', 'soup']
,['sauer', 'sour']
,['Quelle, f', 'source']
,['Süden', 'south']
,['Raum, m', 'space']
,['sprechen', 'speak']
,['Geschwindigkeit, f', 'speed']
,['ausgeben', 'spend']
,['Stall, m', 'spider']
,['Geist, m', 'spirit']
,['prächtig', 'splendid']
,['Löffel, m', 'spoon']
,['Stelle, f, Ort, m', 'spot']
,['ausbreiten', 'spread']
,['Frühling, m', 'spring']
,['Platz, m', 'square']
,['Personal, n', 'staff']
,['Bühne, f', 'stage']
,['Treppe, f', 'stairs']
,['Briefmarke, f', 'stamp']
,['stehen', 'stand']
,['Stern, m', 'star']
,['starren, blicken', 'stare']
,['beginnen', 'start']
,['Staat, m', 'state']
,['Bahnhof, m', 'station']
,['bleiben', 'stay']
,['Stahl, m', 'steel']
,['Schritt, m', 'step']
,['immer noch', 'still']
,['rühren', 'stir']
,['Aktie, f', 'stock']
,['Magen, m', 'stomach']
,['Stein, m', 'stone']
,['Haltestelle, f', 'stop']
,['anhalten', 'stop (verb)']
,['Laden, m', 'store']
,['Sturm, m', 'storm']
,['Geschichte, f', 'story']
,['Ofen, m', 'stove']
,['geradeaus', 'straight']
,['fremd, seltsam', 'strange']
,['Erdbeere, f', 'strawberry']
,['Strom, m, Fluss, m', 'stream']
,['Strasse', 'street']
,['Kraft, f , Stärke, f', 'strength']
,['stark', 'strong']
,['streiten,kämpfen', 'struggle']
,['Student, m,-in, f', 'student']
,['studieren', 'study']
,['Erfolg, m', 'success']
,['erfolgreich', 'successful']
,['solcher,-e,-es', 'such']
,['plötzlich', 'suddenly']
,['genügend', 'sufficient']
,['Zucker, m', 'sugar']
,['empfehlen', 'suggest']
,['Anzug, m', 'suit']
,['passen', 'suit (verb)']
,['passend', 'suitable']
,['Sommer, m', 'summer']
,['Sonne, f', 'sun']
,['Sonntag, m', 'Sunday']
,['Abendessen, n', 'supper']
,['liefern', 'supply']
,['unterstützen', 'support']
,['annehmen', 'suppose']
,['höchster,-e,-es', 'supreme']
,['sicher', 'sure']
,['Oberfläche, f', 'surface']
,['Ueberraschung, f', 'surprise']
,['süss', 'sweet']
,['schwimmen', 'swim']
,['Tisch, f', 'table']
,['nehmen', 'take']
,['reden', 'talk']
,['gross', 'tall']
,['Aufgabe, f', 'task']
,['Geschmack, m', 'taste (noun)']
,['abschmecken', 'taste (verb)']
,['Steuern, pl', 'taxes']
,['Tee, m', 'tea']
,['lehren', 'teach']
,['Lehrer, m, Lehrerin, f', 'teacher']
,['reissen', 'tear (verb)']
,['Tränen, pl', 'tears']
,['Technik, f', 'technique']
,['Telefon, n', 'telephone']
,['Fernsehen, n', 'television']
,['erzählen', 'tell']
,['Temperatur, f', 'temperature']
,['zehn', 'ten']
,['Spannung, f', 'tension']
,['Semester, n', 'term']
,['testen', 'test']
,['als', 'than']
,['danken', 'thank']
,['danke', 'thank you']
,['das', 'that']
,['welcher,-e,-es', 'that (which)']
,['der, die, das', 'the']
,['die', 'the( plural)']
,['Theater, n', 'theater']
,['ihre', 'their']
,['dann', 'then']
,['dort', 'there']
,['deswegen', 'therefore']
,['diese', 'these']
,['sie', 'they']
,['dick', 'thick']
,['dünn', 'thin']
,['Sache, f, Ding, n', 'thing']
,['denken', 'think']
,['Durst, m', 'thirst']
,['dreizehn', 'thirteen']
,['dreissig', 'thirty']
,['dieser,-e,-es', 'this']
,['heute morgen', 'this morning']
,['obwohl', 'though']
,['Gedanke, m', 'thought']
,['tausend', 'thousand']
,['Faden, m', 'thread']
,['drei', 'three']
,['Hals, m', 'throat']
,['durch', 'through']
,['werfen', 'throw']
,['Daumen, m', 'thumb']
,['Donner, m', 'thunder']
,['Donnerstag, m', 'Thursday']
,['so, darum', 'thus']
,['Fahrkarte, f', 'ticket']
,['Kravatte, f', 'tie']
,['Tiger, m', 'tiger']
,['bis', 'till']
,['Zeit, f', 'time']
,['mal', 'times (many)']
,['winzig', 'tiny']
,['Reifen, m', 'tire']
,['müde', 'tired']
,['Titel, m', 'title']
,['zu', 'to']
,['dir', 'to you']
,['heute', 'today']
,['Zehe, f', 'toe']
,['zusammen', 'together']
,['Toilette, f', 'toilet']
,['Tomate, f', 'tomato']
,['morgen', 'tomorrow']
,['Ton, m,Klang, m', 'tone']
,['Zange, f', 'tongs']
,['Zunge, f', 'tongue']
,['auch', 'too']
,['zu viel', 'too much']
,['Zahn, m', 'tooth']
,['Zahnbürste, f', 'toothbrush']
,['Schildkröte, f', 'tortoise']
,['total', 'total']
,['berühren', 'touch']
,['Turm, m', 'tower']
,['Stadt, f', 'town']
,['Handel, m', 'trade']
,['Verkehr, m', 'traffic']
,['Zug, m', 'train']
,['übersetzen', 'translate']
,['reisen', 'travel (verb)']
,['Behandlung, f', 'treatment']
,['Baum, m', 'tree']
,['Reise, f', 'trip']
,['Schwierigkeiten', 'trouble']
,['Hose, f', 'trousers']
,['Lastwagen, m', 'truck']
,['wahr', 'true,']
,['Vertrauen, n, Trust, m', 'trust']
,['Wahrheit, f', 'truth']
,['versuchen', 'try']
,['Dienstag, m', 'Tuesday']
,['Kurve, f, Reihe, f', 'turn']
,['zwölf', 'twelve']
,['zwanzig', 'twenty']
,['zwei mal', 'twice']
,['zwei', 'two']
,['hässlich', 'ugly']
,['Schirm, m', 'umbrella']
,['Onkel, m', 'uncle']
,['unter', 'under']
,['U-Bahn', 'underground']
,['verstehen', 'understand']
,['einmalig', 'unique']
,['Weltall, n', 'universe']
,['Universität, f', 'university']
,['falls nicht', 'unless']
,['bis', 'until']
,['unüblich', 'unusual']
,['auf, nach oben', 'up']
,['bis jetzt', 'up to now']
,['uns', 'us']
,['gebrauchen', 'use']
,['Staubsauger, m', 'vacuum cleaner']
,['Tal, n', 'valley']
,['Wert, m', 'value']
,['verschieden', 'various']
,['weit, ausgedehnt', 'vast']
,['Kalbfleisch, n', 'veal']
,['Gemüse, n', 'vegetable']
,['sehr', 'very']
,['Sieg, m', 'victory']
,['Sicht, f , Ansicht, f', 'view']
,['Dorf, n', 'village']
,['besuchen', 'visit']
,['Stimme, f', 'voice']
,['Lautstärke, f', 'volume']
,['wählen, abstimmen', 'vote']
,['Lohn, m', 'wage']
,['Lastwagen, m', 'wagon']
,['warten', 'wait']
,['Kellner, m', 'waiter']
,['gehen', 'walk (go)']
,['Mauer, f', 'wall']
,['wollen', 'want']
,['Krieg, m', 'war']
,['warm', 'warm']
,['waschen', 'wash']
,['Uhr, f', 'watch (noun)']
,['betrachten', 'watch (verb)']
,['Wasser, n', 'water']
,['Weg, m', 'way']
,['wir', 'we']
,['Waffen, pl', 'weapons']
,['tragen', 'wear (clothes)']
,['Wetter, n', 'weather']
,['Mittwoch, m', 'Wednesday']
,['Woche, f', 'week']
,['Gewicht, n', 'weight']
,['willkommen', 'welcome']
,['Fürsorge, f', 'welfare']
,['gut', 'well']
,['Westen', 'west']
,['nass', 'wet']
,['was', 'what']
,['Rad, n', 'wheel']
,['wann', 'when']
,['wo', 'where']
,['ob', 'whether']
,['welcher,-e,-es', 'which']
,['während', 'while']
,['weiß', 'white']
,['wer, welcher', 'who']
,['ganz', 'whole']
,['welchen,-e,-es', 'whom']
,['wessen', 'whose']
,['warum', 'why']
,['weit', 'wide']
,['Ehefrau, f', 'wife']
,['wild', 'wild']
,['gewinnen', 'win']
,['Wind, m', 'wind']
,['Fenster, n', 'window']
,['Wein, m', 'wine']
,['Winter, m', 'winter']
,['wünschen', 'wish (verb)']
,['mit', 'with']
,['damit', 'with that']
,['darin', 'within']
,['ohne', 'without']
,['Frau, f', 'woman']
,['sich fragen', 'wonder (verb)']
,['wunderbar', 'wonderful']
,['Holz, n', 'wood']
,['Wolle, f', 'wool']
,['Wort, n', 'word']
,['Arbeit, f', 'work (noun)']
,['arbeiten', 'work (verb)']
,['Arbeiter', 'worker']
,['Welt, f', 'world']
,['schlimmer', 'worse']
,['wertlos', 'worthless']
,['schreiben', 'write']
,['falsch', 'wrong']
,['Hof, m,Yard, m', 'yard']
,['Jahr, n', 'year']
,['gelb', 'yellow']
,['gelb', 'yellow']
,['ja', 'yes']
,['gestern', 'yesterday']
,['noch', 'yet']
,['dich, dir', 'you']
,['ihr', 'you (plural)']
,['du, Sie', 'you(singular)']
,['jung', 'young']
,['euer, Ihr', 'your (plural)']
,['dein, Ihr', 'your (singular)']
,['Jugend, f', 'youth']
,['null', 'zero']
,['eine (for feminine)', 'a (indefinite article)']
,['ein (for masculine & neuter)', 'a (indefinite article)']
,['Fähigkeit, f', 'ability']
,['fähig', 'able, capable']
,['etwa', 'about (circa)']
,['über', 'about (concerning)']
,['über, darüber', 'above']
,['im Ausland', 'abroad']
,['abwesend', 'absent']
,['annehmen', 'accept']
,['Unfall, m', 'accident']
,['Konto, n', 'account']
,['erreichen', 'achieve']
,['durch', 'across (through)']
,['handeln', 'act (verb)']
,['Handlung, f', 'action']
,['Tätigkeit, f', 'activity']
,['Schauspieler, m', 'actor']
,['Schauspielerin, f', 'actress']
,['tatsächlich', 'actual']
,['eigentlich', 'actually']
,['hinzufügen', 'add']
,['zusätzlich', 'added']
,['beigefügt', 'additional']
,['Adresse, f', 'address']
,['angemessen', 'adequate']
,['Verwaltung, f', 'administration']
,['erwachsen', 'adult']
,['fortgeschritten', 'advanced']
,['Vorteil, m', 'advantage']
,['Werbung, f', 'advertising']
,['Rat, m', 'advice']
,['Geschäfte, pl', 'affairs (plural)']
,['besorgt', 'afraid']
,['nach', 'after']
,['darnach', 'after that']
,['Nachmittag, m', 'afternoon']
,['nachher', 'afterwards']
,['wieder', 'again']
,['gegen', 'against']
,['Alter, n', 'age']
,['vor', 'ago']
,['zustimmen', 'agree']
,['Vereinbarung, f', 'agreement']
,['Hilfe, f', 'aid (help)']
,['Ziel, n', 'aim']
,['Luft, f', 'air']
,['Flugzeug, n', 'airplane']
,['Flughafen, m', 'airport']
,['Wecker, m', 'alarm clock']
,['Alkohol, m', 'alcohol']
,['lebendig', 'alive']
,['alle', 'all']
,['erlauben', 'allow']
,['fast', 'almost']
,['allein', 'alone']
,['entlang', 'along']
,['schon', 'already']
,['auch', 'also (too)']
,['obwohl', 'although']
,['immer', 'always']
,['unter, zwischen', 'among']
,['Betrag, m', 'amount']
,['vergnügen', 'amuse']
,['alt', 'ancient']
,['und', 'and']
,['und so weiter (or simply usw.)', 'and so on']
,['Winkel, m', 'angle']
,['wütend', 'angry']
,['Tier, n', 'animal']
,['Fessel, f', 'ankle']
,['ankündigen', 'announce']
,['jährlich', 'annual']
,['ein anderer,-e,-es', 'another']
,['Antwort, f', 'answer']
,['Ameise, f', 'ant']
,['jeder, e, -es', 'any']
,['irgend jemand', 'anyone']
,['irgend etwas', 'anything']
,['irgendwo', 'anywhere']
,['Wohnung, f', 'apartment']
,['erscheinen', 'appear']
,['Appetit, m', 'appetite']
,['Apfel, m', 'apple']
,['anwenden', 'apply']
,['sich nähern', 'approach']
,['passend', 'appropriate']
,['Billigung, f', 'approval']
,['ungefähr', 'approximately']
,['Aprikose, f', 'apricot']
,['April, m', 'April']
,['Gebiet, n', 'area']
,['Beweis, m', 'argument']
,['Arm, m', 'arm']
,['Sessel, m', 'armchair']
,['Waffen, pl', 'arms (plural)']
,['Armee, f', 'army']
,['herum', 'around']
,['Ankunft, f', 'arrival']
,['ankommen', 'arrive']
,['Kunst, f', 'art']
,['Artikel, m', 'article']
,['Künstlerin, f', 'artist (feminine)']
,['Künstler, m,', 'artist (masculine)']
,['wie', 'as (like)']
,['als', 'as (when)']
,['bitten', 'ask (beg)']
,['fragen', 'ask (question)']
,['Anblick, m', 'aspect']
,['Versammlung, f', 'assembly']
,['Zuweisung, f', 'assignment']
,['Beistand, m, Assistenz, f', 'assistance']
,['Verband, m', 'association']
,['annehmen', 'assume']
,['um', 'at (hour)']
,['an', 'at (place)']
,['endlich', 'at last']
,['wenigstens', 'at least']
,['höchstens', 'at most']
,['zur gleichen Zeit', 'at the same time']
,['angreifen', 'attack']
,['Versuch, m', 'attempt']
,['Achtung, f', 'attention']
,['Haltung, f', 'attitude']
,['Anwalt, m', 'attorney']
,['August, m', 'August']
,['Tante, f', 'aunt']
,['Schriftstellerin, f', 'author (feminine)']
,['Schriftsteller, m,', 'author (masculine)']
,['Herbst, m', 'autumn']
,['käuflich', 'available']
,['vermeiden', 'avoid']
,['erwachen', 'awake']
,['aufgeweckt', 'aware']
,['weg', 'away']
,['Kohl, m', 'cabbage']
,['Café, n', 'café']
,['Kuchen, m', 'cake']
,['Kalb, n', 'calf']
,['rufen, anrufen', 'call']
,['Lager, n', 'camp']
,['können', 'can']
,['Kerze, f', 'candle']
,['Aufnahmefähigkeit, f', 'capacity']
,['Kapital, n', 'capital']
,['Kapitän, m', 'captain']
,['Wagen, m, Auto, n', 'car']
,['Karte, f', 'card']
,['sorgen', 'care']
,['Karriere, f', 'career']
,['vorsichtig', 'careful']
,['Teppich, m', 'carpet']
,['Rübe, f, Karrotte, f', 'carrot']
,['tragen', 'carry']
,['Fall, m', 'case, instance']
,['Kassierer, m,', 'cashier']
,['Katze', 'cat']
,['fangen', 'catch']
,['Kathedrale, f', 'cathedral']
,['Vieh, n', 'cattle']
,['Blumenkohl, m', 'cauliflower']
,['Grund, m', 'cause']
,['Zelle, f', 'cell']
,['Keller, m', 'cellar']
,['Zentrum, n', 'center']
,['zentral', 'central']
,['Jahrhundert, n', 'century']
,['gewiss', 'certain']
,['gewiss', 'certainly']
,['Kette, f', 'chain']
,['Stuhl, m', 'chair']
,['Vordsitzender, m', 'chairman']
,['Chance, f', 'chance']
,['veränderlich', 'changable']
,['Wechsel', 'change (noun)']
,['wechseln', 'change (verb)']
,['Kapitel, f', 'chapter']
,['Charakter, m', 'character']
,['Merkmal', 'characteristics']
,['beladen', 'charge']
,['billig', 'cheap']
,['prüfen', 'check (verb)']
,['Wange, f', 'cheek']
,['Käse, m', 'cheese']
,['chemisch', 'chemical']
,['Kirsche, f', 'cherry']
,['Brust, f', 'chest']
,['Hühnchen, n', 'chicken']
,['Leiter, m', 'chief']
,['Kind, n', 'child']
,['Kindheit, f', 'childhood']
,['kühlen', 'chill']
,['Kinn, n', 'chin']
,['Porzellan, n', 'china']
,['chinesisch', 'chinese']
,['Schokolade, f', 'chocolate']
,['Wahl, f', 'choice']
,['wählen, auswählen', 'choose']
,['christlich', 'christian']
,['Weihnachten', 'christmas']
,['Kirche, f', 'church']
,['Zigarette, f', 'cigarette']
,['Kreis, m', 'circle']
,['Umstände, pl', 'circumstances']
,['Bürger, m', 'citizen']
,['Stadt, f', 'city']
,['bürgerlich', 'civil']
,['Anspruch, m', 'claim']
,['Klasse, f', 'class']
,['Lehm, m', 'clay']
,['sauber', 'clean']
,['klar, hell', 'clear']
,['Kunde, m', 'client']
,['Uhr, f', 'clock(tower)']
,['Armbanduhr, f', 'clock,watch']
,['nahe, bei', 'close']
,['eng', 'closely']
,['Kleider, pl', 'clothes']
,['Wolke, f', 'cloud']
,['Club, m', 'club']
,['Küste, f', 'coast']
,['Mantel, m', 'coat']
,['Kaffee, m', 'coffee']
,['kalt', 'cold']
,['Kragen, m', 'collar']
,['Sammlung, f', 'collection']
,['College, n', 'college']
,['Farbe, f', 'color']
,['Säule, f', 'column']
,['Kamm, m', 'comb']
,['Verbindung, f', 'combination']
,['kommen', 'come']
,['zurückkommen', 'come back']
,['befehlen', 'command']
,['Handel, m', 'commerce']
,['Werbespot, m', 'commercial']
,['Kommission, f', 'commission']
,['Komittee, n', 'committee']
,['gewöhnlich', 'common']
,['Verbindung, f', 'communication']
,['Gesellschaft, f', 'company']
,['vergleichen', 'compare']
,['Wettbewerb, m', 'competition']
,['vollständig', 'complete']
,['Hautfarbe, f', 'complexion']
,['Kamarad, m', 'comrade']
,['Planung, f', 'concept']
,['betreffen', 'concern']
,['Ergebnis, n', 'conclusion']
,['Bedingung, f', 'condition']
,['Verhalten, n', 'conduct']
,['Besprechung, f', 'conference']
,['bekennen', 'confess']
,['Zutrauen, n', 'confidence']
,['Konflikt, m', 'conflict']
,['Kongress, m', 'congress']
,['Verbindung, f', 'connection']
,['erwägen, überlegen', 'consider']
,['beträchtlich', 'considerable']
,['Bauwerk, n', 'construction']
,['kontaktieren', 'contact']
,['enthalten', 'contain']
,['zeitgenössisch', 'contemporary']
,['Inhalt, m', 'content']
,['fortsetzen', 'continue']
,['Vertrag, m', 'contract']
,['Gegenteil, n', 'contrary']
,['Gegensatz, m', 'contrast']
,['Kontrolle, f', 'control']
,['Gespräch, n', 'conversation']
,['Ueberzeugung, f', 'conviction']
,['überzeugen', 'convince']
,['kochen', 'cook']
,['Koch, m, Köchin, f', 'cook']
,['kühl', 'cool']
,['Seil, n', 'cord']
,['Ecke, f', 'corner']
,['Gesellschaft, f', 'corporation']
,['richtig', 'correct']
,['kosten', 'cost']
,['Ratsversammlung, f', 'council']
,['zählen, berechnen', 'count']
,['Land, n', 'country']
,['Grafschaft, f', 'county']
,['Paar, n', 'couple']
,['Lauf, m, Verlauf, m', 'course']
,['Gericht, n', 'court']
,['Cousin, m, Cousine, f', 'cousin']
,['bedecken', 'cover']
,['Kuh, f', 'cow']
,['Sahne, f', 'cream']
,['erschaffen', 'create']
,['Kredit, m', 'credit']
,['Verbrechen, n', 'crime']
,['Krise, f', 'crisis']
,['kritisch', 'critical']
,['Kreuz, n', 'cross']
,['Menge, f', 'crowd']
,['Krone, f', 'crown']
,['weinen', 'cry, weep']
,['Gurke, f', 'cucumber']
,['kulturell', 'cultural']
,['Kultur, f', 'culture']
,['Tasse, f', 'cup']
,['Schrank, m', 'cupboard']
,['laufend', 'current']
,['Vorhang, m', 'curtain']
,['Zoll, m', 'customs']
,['schneiden', 'cut']
,['', ' ']
,['Papa, m', 'daddy']
,['täglich', 'daily']
,['tanzen', 'dance']
,['Gefahr, f', 'danger']
,['gefährlich', 'dangerous']
,['dunkel', 'dark']
,['Daten, pl', 'data']
,['Datum, n', 'date']
,['Tochter, f', 'daughter']
,['Tag, m', 'day']
,['tot', 'dead']
,['taub', 'deaf']
,['Abmachung, f', 'deal']
,['teuer, lieb', 'dear']
,['Dezember', 'December']
,['entscheiden', 'decide']
,['Entscheidung, f', 'decision']
,['bekanntgeben', 'declare']
,['tief', 'deep']
,['Verteidigung, f', 'defense']
,['Grad, m', 'degree']
,['Anfrage, f', 'demand']
,['verlangen', 'demand']
,['demokratisch', 'democratic']
,['Zahnarzt, m', 'dentist']
,['abreisen', 'depart, leave']
,['Abteilung, f', 'department']
,['Abfahrt, f', 'departure']
,['Tiefe, f', 'depth']
,['beschreiben', 'describe']
,['Wüste, f', 'desert']
,['entwerfen', 'design']
,['begehren', 'desire']
,['Schreibtisch, m', 'desk']
,['trotz', 'despite']
,['Dessert, n', 'dessert']
,['Detail, f', 'detail']
,['Detektiv, m', 'detective']
,['bestimmen', 'determine']
,['entschlossen', 'determined']
,['entwickeln', 'develop']
,['Entwicklung, f', 'development']
,['Gerät, n', 'device']
,['ergeben', 'devoted']
,['Wörterbuch, n', 'dictionary']
,['sterben', 'die']
,['Unterschied, m', 'difference']
,['verschieden', 'different']
,['schwierig', 'difficult']
,['Esszimmer, n', 'dining room']
,['Abendessen, n', 'dinner']
,['lenken', 'direct']
,['Richtung, f', 'direction']
,['direkt', 'directly']
,['Direktor, m', 'director']
,['schmutzig', 'dirty']
,['enttäuscht', 'disappointed']
,['entdecken', 'discover']
,['besprechen', 'discuss']
,['Besprechung', 'discussion']
,['Krankheit, f', 'disease']
,['Distanz, f', 'distance']
,['verteilen', 'distribute']
,['Distrikt, m', 'district']
,['geteilt', 'divided']
,['Abteilung, f', 'division']
,['tun, machen', 'do']
,['Arzt, m, Aerztin, f', 'doctor']
,['Hund, m', 'dog']
,['häuslich', 'domestic']
,['herrschend', 'dominant']
,['Esel, m', 'donkey']
,['Türe, f', 'door']
,['doppelt', 'double']
,['Zweifel, m', 'doubt']
,['unten, hinunter', 'down']
,['Dutzend, n', 'dozen']
,['dramatisch', 'dramatic']
,['zeichnen', 'draw']
,['Schublade, f', 'drawer']
,['Traum, m', 'dream']
,['Kleid, n', 'dress']
,['trinken', 'drink']
,['Auto fahren', 'drive']
,['betrunken', 'drunk']
,['trocken', 'dry']
,['Ente, f', 'duck']
,['Gebühr, f', 'due']
,['während', 'during']
,['Staub, m', 'dust']
,['Pflicht, f', 'duty']
,['Wohnung, f', 'dwelling']
,['jeder, -e, -es', 'each']
,['Ohr, n', 'ear']
,['früh', 'early']
,['verdienen', 'earn']
,['Erde, f', 'earth']
,['Osten', 'east']
,['leicht', 'easy']
,['essen', 'eat']
,['Wirtschaft, f', 'economy']
,['Kante, f', 'edge']
,['Herausgeber, m', 'editor']
,['Erziehung, f, Bildung, f', 'education']
,['Wirkung, f', 'effect']
,['wirksam', 'effective']
,['Anstrengung, f', 'effort']
,['Ei, n', 'egg']
,['acht', 'eight']
,['beide', 'either']
,['Ellbogen, m', 'elbow']
,['Wahl, f', 'election']
,['elektrisch', 'electric']
,['elektronisch', 'electronic']
,['Element, n', 'element']
,['Elefant, m', 'elephant']
,['Fahrstuhl, m, Lift, m', 'elevator']
,['elf', 'eleven']
,['sonst', 'else']
,['gefühlsmässig', 'emotional']
,['Angestellter, m', 'employee']
,['leer', 'empty']
,['Ende, n', 'end']
,['Feind, m', 'enemy']
,['Energie, f', 'energy']
,['Motor, m', 'engine']
,['geniessen', 'enjoy']
,['genug', 'enough']
,['eintreten', 'enter']
,['ganzer', 'entire']
,['Eingang, m', 'entrance']
,['Briefumschlag, m', 'envelope']
,['gleich', 'equal']
,['Ausrüstung, f', 'equipment']
,['entkommen', 'escape']
,['besonders', 'especially']
,['wesentlich', 'essential']
,['einrichten', 'establish']
,['Liegenschaft, f', 'estate']
,['geschätzt', 'estimated']
,['sogar', 'even A622']
,['Abend, m', 'evening']
,['Ereignis, n', 'event']
,['schliesslich', 'eventually']
,['jemals, immer', 'ever']
,['jeden,-e,-es', 'every']
,['jeder', 'everybody']
,['jeder', 'everyone']
,['alles', 'everything']
,['überall', 'everywhere']
,['Beweis, m', 'evidence']
,['Übel, n', 'evil']
,['genau', 'exactly']
,['Beispiel, f', 'example']
,['ausgezeichnet', 'excellent']
,['ausser', 'except']
,['Wechsel, m', 'exchange']
,['Geschäftsführer, m', 'executive']
,['Uebung, f', 'exercise']
,['existieren', 'exist']
,['Dasein, n', 'existence']
,['Ausgang, m', 'exit']
,['erwarten', 'expect']
,['Auslagen, pl', 'expenses']
,['teuer', 'expensive']
,['Erfahrung, f', 'experience']
,['Experiment, n', 'experiment']
,['erklären', 'explain']
,['ausdrücken', 'express']
,['Ausdruck, m', 'expression']
,['erweitert', 'extended']
,['Ausdehnung, f', 'extent']
,['zusätzlich', 'extra']
,['äusserst', 'extreme']
,['Auge, n', 'eye']
,['Gesicht, n', 'face']
,['Möglichkeiten', 'facilities']
,['Tatsache, f', 'fact']
,['Faktor, m', 'factor']
,['Fabrik, f', 'factory']
,['fehlschlagen', 'fail']
,['Versagen, n', 'failure']
,['ehrlich', 'fair']
,['eher', 'fairly']
,['Märchen, n', 'fairy tale']
,['Glauben, m', 'faith']
,['fallen', 'fall']
,['falsch', 'false,']
,['gewohnt, vertraut', 'familiar']
,['Familie, f', 'family']
,['weit', 'far']
,['Bauernhof, m', 'farm']
,['Mode, f', 'fashion']
,['schnell', 'fast']
,['fett', 'fat']
,['Vater, m', 'father']
,['Fehler, m', 'fault']
,['Gefallen, m', 'favor']
,['Angst, f', 'fear']
,['Eigenschaften', 'features']
,['Februar, m', 'February']
,['ernähren, füttern', 'feed']
,['sich fühlen', 'feel (good)']
,['Gefühl, n', 'feeling']
,['beglückwünschen', 'felicitate']
,['weiblich', 'female']
,['holen', 'fetch']
,['wenig', 'few']
,['Feld, n', 'field']
,['fünfzehn', 'fifteen']
,['fünfzig', 'fifty']
,['Feige, f', 'fig']
,['Kampf, m', 'fight']
,['herausfinden', 'figure out']
,['Akte, f', 'file']
,['füllen', 'fill']
,['Film, m', 'film']
,['endlich', 'finally']
,['finden', 'find']
,['fein, schön', 'fine']
,['Finger, m', 'finger']
,['beenden', 'finish (verb)']
,['Feuer, n', 'fire']
,['erster,-e,-es', 'first']
,['Fisch, m', 'fish']
,['fünf', 'five']
,['Wohnung', 'flat']
,['flach', 'flat (adj.)']
,['Fleisch', 'flesh (body)']
,['Boden, m', 'floor']
,['Mehl, n', 'flour']
,['fliessen', 'flow']
,['Blume, f', 'flower']
,['Fliege, f', 'fly (insect)']
,['fliegen', 'fly (verb)']
,['folgen', 'follow']
,['Nahrung, f, Essen, n', 'food']
,['Fuss, m', 'foot']
,['für', 'for']
,['verboten', 'forbidden']
,['Kraft, f', 'force']
,['fremd, ausländisch', 'foreign']
,['Wald, m', 'forest']
,['vergessen', 'forget']
,['vergeben', 'forgive']
,['Gabel, f', 'fork']
,['Form, f', 'form']
,['früherer', 'former']
,['vierzig', 'forty']
,['Brunnen, m', 'fountain']
,['vier', 'four']
,['vierzehn', 'fourteen']
,['Fuchs, m', 'fox']
,['Rahmen, m', 'frame']
,['gratis', 'free']
,['frei', 'free (not occupied)']
,['häufig', 'frequently']
,['frisch', 'fresh']
,['Freitag, m', 'Friday']
,['Freund, m, freundin, f', 'friend']
,['freundlich', 'friendly']
,['erschrecken', 'frighten']
,['von', 'from']
,['Vorderseite, f', 'front']
,['voll', 'full']
,['grundlegend', 'fundamental']
,['lustig', 'funny']
,['Möbel, pl', 'furniture']
,['weiterer, -e, -es', 'further']
,['Zukunft, f', 'future']
,['Gewinn, m', 'gain']
,['Spiel, n', 'game']
,['Garten, m', 'garden']
,['Gas, n', 'gas']
,['Benzin, n', 'gasoline']
,['allgemein', 'general']
,['bekommen', 'get']
,['Mädchen, n', 'girl']
,['geben', 'give']
,['fröhlich, froh', 'glad']
,['gerne', 'gladly']
,['Glas, n', 'glass']
,['Brille, f', 'glasses']
,['gehen', 'go']
,['Ziel, n', 'goal']
,['Gott, n', 'God']
,['Gold, n', 'gold']
,['Goldfisch, m', 'goldfish']
,['gut', 'good']
,['auf Wiedersehen', 'good-bye']
,['Waren, pl', 'goods']
,['Gans, f', 'goose']
,['Regierung, f', 'government']
,['allmählich', 'gradually']
,['Grossvater, m', 'grandfather']
,['Grossmutter, f', 'grandmother']
,['Gras, n', 'grass']
,['grau', 'gray']
,['grün', 'green']
,['grün', 'green']
,['Wünsche, pl', 'greetings']
,['grau', 'grey']
,['Boden, m', 'ground']
,['Gruppe, f', 'group']
,['wachsen', 'grow']
,['vermuten', 'guess']
,['Gast, m', 'guest']
,['Gewehr, n', 'gun']
,['Kerl, m', 'guy']
,['Haare, pl', 'hair']
,['halb', 'half']
,['Halle, f', 'hall']
,['Schinken, m', 'ham']
,['Hammer, m', 'hammer']
,['Hamster, m', 'hamster']
,['Hand, f', 'hand']
,['Handtasche, f', 'handbag']
,['Taschentuch, n', 'handkerchief']
,['umgehen mit', 'handle']
,['hängen', 'hang']
,['geschehen', 'happen']
,['glücklich', 'happy']
,['hard', 'hard']
,['kaum', 'hardly']
,['Ernte, f', 'harvest']
,['Hut, m', 'hat']
,['hassen', 'hate']
,['haben', 'have']
,['er', 'he']
,['Kopf, m', 'head']
,['Gesundheit, f', 'health']
,['gesund', 'healthy']
,['hören', 'hear']
,['Herz, n', 'heart']
,['Hitze, f', 'heat']
,['schwer', 'heavy']
,['Hölle, f', 'hell']
,['Hilfe', 'help (noun)']
,['helfen', 'help (verb)']
,['Huhn, n', 'hen']
,['hier', 'here']
,['Held, m', 'hero']
,['hoch', 'high']
,['Landstrasse, f', 'highway']
,['Hügel, m', 'hill']
,['ihn, sie, es', 'him,her, it']
,['sein', 'his']
,['Geschichte, f', 'history']
,['schlagen', 'hit']
,['halten', 'hold']
,['Loch, n', 'hole']
,['Ferien, pl', 'holiday']
,['zuhause', 'home, at home']
,['Ehre, f', 'honor']
,['Hoffnung, f', 'hope']
,['schrecklich', 'horrible']
,['Pferd, n', 'horse']
,['Spital, n', 'hospital']
,['heiss', 'hot']
,['Hotel, n', 'hotel, inn']
,['Stunde, f', 'hour']
,['Haus, n', 'house']
,['wie', 'how']
,['wie auch immer', 'however']
,['riesig', 'huge']
,['menschlich', 'human']
,['hundert', 'hundred']
,['hungrig', 'hungry']
,['sich beeilen', 'hurry']
,['verletzen', 'hurt, injure']
,['Ehemann, m', 'husband']
,['ich', 'I']
,['Eis, n', 'ice']
,['Eiskrem, Eis', 'ice cream']
,['Idee, f', 'idea']
,['ideal', 'ideal']
,['wenn', 'if']
,['Bild, n', 'image']
,['sich vorstellen', 'imagine']
,['sofort', 'immediately']
,['Einfluss, m', 'impact']
,['wichtig', 'important']
,['unmöglich', 'impossible']
,['verbessern', 'improve']
,['in', 'in']
,['vor', 'in front of']
,['trotz', 'in spite of']
,['Zoll, m', 'inch']
,['beinhalten', 'include']
,['zunehmen', 'increase']
,['tatsächlich', 'indeed']
,['unabhängig', 'independent']
,['Inhaltsverzeichnis', 'index']
,['Zeigefinger', 'index finger']
,['Einfluss, m', 'influence']
,['anfänglich', 'initial']
,['innerer, -e, -es', 'inner']
,['Insekt, n', 'insect']
,['drinnen', 'inside']
,['anstatt', 'instead']
,['Interesse', 'interest']
,['interessant', 'interesting']
,['Innere, f', 'interior']
,['in.....hinein', 'into']
,['einladen', 'invite']
,['verwickeln', 'involve']
,['Eisen, n', 'iron']
,['Insel, f', 'island']
,['Problem, n', 'issue']
,['es', 'it']
,['es ist kalt', "it's cold"]
,['es ist neblig', "it's foggy"]
,['es friert Kälte ein', "it's freezing"]
,['es ist heiß', "it's hot"]
,['es ist nett', "it's nice"]
,['es ist regnerisch', "it's rainy"]
,['es ist schneebedeckt', "it's snowy"]
,['es ist sonnig', "it's sunny"]
,['es ist windig', "it's windy"]
,['Jacke, f', 'jacket']
,['Marmelade, f', 'jam']
,['Januar, m', 'January']
,['Job, m', 'job']
,['sich anschliessen', 'join']
,['Richter, m', 'judge']
,['Saft, m', 'juice']
,['Juli, m', 'July']
,['springen', 'jump']
,['Juni, m', 'June']
,['nur', 'just (only)']
,['Gerechtigkeit, f', 'justice']
,['halten', 'keep']
,['Schlüssel, m', 'key']
,['töten', 'kill']
,['Art, f', 'kind']
,['König, m', 'king']
,['Küche, f', 'kitchen']
,['Kätzchen, n', 'kitten']
,['Knie, n', 'knee']
,['Messer, n', 'knife']
,['kennen', 'know (person)']
,['können', 'know to']
,['Wissen, n', 'knowledge']
,['Arbeit, f', 'labor']
,['mangeln', 'lack']
,['Leiter, f', 'ladder']
,['Dame, f', 'lady']
,['See, m', 'lake']
,['Lampe, f', 'lamp']
,['Land, n', 'land']
,['Sprache, d', 'language']
,['breit', 'large']
,['letzter,-e,-es', 'last']
,['letzte', 'last (previous)']
,['spät', 'late']
,['lachen', 'laugh']
,['Recht, n', 'law']
,['legen', 'lay']
,['führen', 'lead']
,['Anführer, d', 'leader']
,['lernen', 'learn']
,['weggehen', 'leave']
,['links', 'left']
,['Bein, n', 'leg']
,['gesetzlich', 'legal']
,['Zitrone, f', 'lemon']
,['Länge, f', 'length']
,['weniger', 'less']
,['lassen', 'let (allow)']
,['Brief, m', 'letter']
,['Bibliothek, f', 'library']
,['liegen', 'lie']
,['lügen', 'lie']
,['Leben, f', 'life']
,['heben', 'lift (verb)']
,['leicht', 'light (adjective)']
,['Licht', 'light (electr)']
,['Blitz, m', 'lightning']
,['wie', 'like (as)']
,['mögen', 'like (verb)']
,['wahrscheinlich', 'likely']
,['Linie, f', 'line']
,['Lippe, f', 'lip']
,['flüssig', 'liquid']
,['Liste, f', 'list']
,['hören, zuhören', 'listen']
,['Literatur, f', 'literature']
,['wenig', 'little (amount)']
,['klein', 'little (size)']
,['leben', 'live']
,['wohnen', 'live, dwell']
,['lokal', 'local']
,['gelegen', 'located']
,['Standort, m', 'location']
,['Schloss, n', 'lock (noun)']
,['lang', 'long (object)']
,['lange', 'long (time)']
,['schauen', 'look']
,['verlieren', 'lose']
,['Verlust, m', 'loss']
,['Haufen, m', 'lot']
,['laut', 'loud']
,['Liebe, f', 'love (noun)']
,['lieben', 'love (verb)']
,['leise', 'low']
,['Glück, n', 'luck']
,['Mittagessen, n', 'lunch']
,['', ' ']
,['Maschine, f', 'machine']
,['Magazin, n', 'magazine']
,['Post, f', 'mail']
,['instandhalten', 'maintain']
,['Mehrheit, f', 'majority']
,['machen', 'make']
,['Mann, m, Mensch, m', 'man']
,['Art, f', 'manner']
,['viele', 'many']
,['Landkarte, f', 'map']
,['März, m', 'March']
,['marschieren', 'march']
,['kennzeichnen', 'mark']
,['Markt, m', 'market']
,['Hochzeit, f', 'marriage']
,['verheiratet', 'married']
,['Messe, f', 'mass']
,['Material, n', 'material']
,['Gegenstand, m', 'matter']
,['Maximum, n', 'maximum']
,['Mai, m', 'May']
,['dürfen', 'may']
,['vielleicht', 'maybe']
,['mich (accusative), mir (dative)', 'me']
,['Wiese, f', 'meadow']
,['Mahlzeit, f', 'meal']
,['meinen, denken', 'mean']
,['Bedeutung, f', 'meaning']
,['Mittel, n', 'means']
,['unterdessen', 'meanwhile']
,['Mass, n', 'measure']
,['Fleisch, n', 'meat']
,['treffen', 'meet']
,['Mitglied, n', 'member']
,['Gedächtnis, n', 'memory']
,['erwähnen', 'mention']
,['kaum', 'merely']
,['Botschaft, f', 'message']
,['Metall, n', 'metal']
,['Methode, f', 'method']
,['Mittag', 'midday, noon']
,['mittlerer,-e,-es', 'middle']
,['Mitternacht', 'midnight']
,['Meile, f', 'mile']
,['Milch, f', 'milk']
,['Million, f', 'million']
,['Sinn, m, Geist, m', 'mind']
,['Minimum, n', 'minimum']
,['Minister, m', 'minister']
,['Minute, f', 'minute']
,['Spiegel, m', 'mirror']
,['Fräulein', 'Miss']
,['vermissen', 'miss (verb)']
,['Fehler, m', 'mistake']
,['modern', 'modern']
,['Augenblick, m, Moment, m', 'moment']
,['Montag, m', 'Monday']
,['Geld, n', 'money']
,['Monat, m', 'month']
,['Mond, m', 'moon']
,['mehr', 'more']
,['mehr...als', 'more... than']
,['Morgen, m', 'morning']
,['die meisten', 'most']
,['Mutter, f', 'mother']
,['Bewegung, f', 'motion']
,['Motor, m', 'motor']
,['Berg, m', 'mountain']
,['Maus, f', 'mouse']
,['Mund, m', 'mouth']
,['bewegen', 'move']
,['Bewegung, f', 'movement']
,['Herr', 'Mr.']
,['Frau', 'Mrs.']
,['viel', 'much']
,['Mord, m', 'murder']
,['Musik, f', 'music']
,['müssen', 'must']
,['mein,-e', 'my']
,['mich', 'myself']
,['Nagel, m', 'nail']
,['Name, m', 'name']
,['Serviette, f', 'napkin']
,['eng', 'narrow']
,['böse, schlimm', 'nasty']
,['natürlich', 'natural']
,['Natur, f', 'nature']
,['nahe', 'near']
,['notwendig', 'necessary']
,['Hals, m', 'neck']
,['brauchen', 'need']
,['Nadel, f', 'needle']
,['Nachbar, m', 'neighbor']
,['Nachbarschaft, f', 'neighborhood']
,['weder...noch', 'neither...nor']
,['nie', 'never']
,['trotzdem', 'nevertheless']
,['neu', 'new']
,['Nachrichten, pl', 'news']
,['Zeitung, f', 'newspaper']
,['nächster,-e,-es', 'next']
,['nett', 'nice']
,['Nacht, f', 'night']
,['neun', 'nine']
,['neunzehn', 'nineteen']
,['neunzig', 'ninety']
,['nein', 'no']
,['niemand', 'nobody']
,['nicken', 'nod']
,['Lärm, m', 'noise']
,['niemand', 'none']
,['weder', 'nor']
,['normal', 'normal']
,['Norden', 'north']
,['Nase, f', 'nose']
,['nicht', 'not']
,['Notiz, f', 'note']
,['nichts', 'nothing']
,['bemerken', 'notice']
,['Roman, m', 'novel']
,['November, m', 'November']
,['jetzt', 'now']
,['nirgendwo', 'nowhere']
,['Zahl, f', 'number']
,['Krankenschwester, f', 'nurse']
,['Nuss, f', 'nut']
,['Eiche, f', 'oak']
,['beobachten', 'observe']
,['erhalten', 'obtain']
,['offensichtlich', 'obvious']
,['Gelegenheit, f', 'occasion']
,['vorfallen', 'occur']
,['Oktober, m', 'October']
,['von', 'of']
,['natürlich, gewiss', 'of course']
,['weg', 'off']
,['anbieten', 'offer']
,['Büro, n', 'office']
,['Offizier, Beamter', 'officer']
,['offiziell', 'official']
,['oft', 'often']
,['Oel, n', 'oil']
,['alt', 'old']
,['auf', 'on']
,['pünktlich', 'on time,in time']
,['ein mal', 'once']
,['ein, eine', 'one']
,['man', 'one(impers.)']
,['sich', 'oneself']
,['Zwiebel, f', 'onion']
,['nur', 'only']
,['öffnen', 'open']
,['Meinung, f', 'opinion']
,['Gelegenheit, f', 'opportunity']
,['gegenüberstehend', 'opposite']
,['oder', 'or']
,['Orange, f', 'orange']
,['orangegelb', 'orange (color)']
,['Orchester, n', 'orchestra']
,['bestellen', 'order']
,['gewöhnlich', 'ordinary']
,['Organisation, f', 'organization']
,['original', 'original']
,['Morgen, m', 'orning']
,['anderer,-e,-es', 'other']
,['sonst', 'otherwise']
,['unser, -e', 'our']
,['draussen', 'outside']
,['Ofen', 'oven']
,['über', 'over']
,['Mantel, m', 'overcoat']
,['eigener,-e,-es', 'own']

    ]