greek_array=[
['ὁ ἡ τό', 'the']
,['αὐτός αὐτή αὐτό', 'him- her- itself etc. (for emphasis); the same (with article); (pron.) him, her, it etc. (in oblique cases)']
,['καί', 'and, also, even; καί...καί both...and']
,['δέ', 'and; but']
,['τίς τί', 'who? what? which? (interrog. pron./adj.)']
,['εἰμί, ἔσομαι, impf. ἦν, infin. εἶναι', 'be, exist']
,['οὗτος αὕτη τοῦτο', 'this, these; μετὰ ταῦτα after this']
,['ἤ', 'or; than (after a comparative); ἤ...ἤ either...or']
,['ἐν', 'in, among (+dat.)']
,['μέν...δέ', 'on the one hand...on the other hand (often untranslated); μέν (by itself) indeed']
,['τις τι', 'someone, something, anyone, anything, some, any (enclitic indef. pron./adj.)']
,['ὅς ἥ ὅ', 'who, which, that']
,['γάρ', 'for (explanatory), indeed, in fact (confirming)']
,['οὐ, οὐκ, οὐχ', 'not (with indicative verbs)']
,['λέγω, ἐρῶ, εἶπον, εἴρηκα, λέλεγμαι, ἐλέχθην and ἐρρήθην', 'say, speak (of), recount; pick up, collect, count']
,['ὡς', 'as, since; (introducing purpose clause) so that (+subj./opt.); (introducing indir. statement) that']
,['τε', 'and; τε…τε both…and']
,['εἰς', 'into, to, towards (+acc.)']
,['ἐπί', 'at (+gen.); on (+dat.); on to, against (+acc.)']
,['κατά', 'down, down (from or along), throughout, according to; κατὰ γῆν by land; κατὰ φύσιν in accordance with nature; κατ’ ἔθνη by nations; καθ᾿ἕνα one by one.']
,['ἐγώ ἐμοῦ, (pl.) ἡμεῖς, ἡμῶν', 'I, we']
,['πρός', 'from the side of, in the presence of (+gen.); near, at, in addition to (+dat.); to, towards, in relation to (+acc.)']
,['γίγνομαι, γενήσομαι, 2 aor. ἐγενόμην, γέγονα, γεγένημαι, ἐγενήθην', 'become; be born; happen, be']
,['ἐάν (εἰ-ἄν)', 'if (+subj.)']
,['διά', 'through, during, because of (+gen., acc.)']
,['ἀλλά', 'but']
,['πᾶς πᾶσα πᾶν', 'every, all; whole (with article)']
,['ἔχω, ἕξω or σχήσω, 2 aor. ἔσχον, ἔσχηκα, impf. εἶχον', 'have, hold, keep']
,['ἐκ, ἐξ', 'from, out of (+gen.)']
,['πολύς πολλή πολύ', 'much, many; ὡς ἐπὶ τὸ πολύ for the most part']
,['περί', 'around, about; concerning (+gen.)']
,['μή', 'not (marks the negative as subjective or conditional); εἰ μή if not, except']
,['ὅστις ἥτις ὅ τι', 'anyone who, anything which; (in indir. quest.) who, which, what']
,['ἄν', '[marks verbs as potential (with optative), or generalizing (with subjunctive)]']
,['σύ, σοῦ, (pl.) ὑμεῖς, ὑμῶν', 'you']
,['ἀνά', 'up, on; throughout']
,['ὅτι', 'because, that; (with superl.) as...as possible']
,['εἰ', 'if (+indic. or opt.); εἴπερ if indeed']
,['ἄλλος ἄλλη ἄλλο', 'other, another']
,['ἀπό', 'from (+gen.)']
,['φημί, φήσω, impf. ἔφην', 'say, assert, declare; οὐ φημί deny, refuse, say that...not']
,['ὑπό', 'under (+gen., dat.); by (+gen. of personal agent); down under (+acc.)']
,['ποιέω, ποιήσω, ἐποίησα, πεποίηκα, πεποίημαι, ἐποιήθην', 'make, produce, cause, do; (mid.) consider, reckon']
,['οὖν', 'therefore, accordingly; at any rate']
,['λόγος λόγου, ὁ', 'word, speech, discourse; thought, reason, account']
,['παρά', 'from (+gen.); beside (+dat.); to, to the side of, contrary to (+acc.)']
,['οὕτως', 'in this way']
,['πρότερος προτέρα πρότερον', 'before, earlier; τὸ πρότερον previously, before']
,['θεός θεοῦ, ὁ/ἡ', 'god, goddess']
,['μετά', 'with (+gen.); after (+acc.)']
,['ἑαυτοῦ ἑαυτῆς ἑαυτοῦ', 'him- her- itself (reflexive pron.)']
,['μέγας μεγάλη μέγα', 'big, great, powerful']
,['οὐδέ', 'and not, but not, nor; οὐδέ...οὐδέ not even...nor yet']
,['ἐκεῖνος ἐκείνη ἐκεῖνο', 'that person or thing; ἐκεῖνος…οὗτος the former…the latter']
,['τοιοῦτος τοιαύτη τοιοῦτο', 'such, of such a sort']
,['οὐδείς οὐδεμία οὐδέν', 'no one, nothing']
,['εἶπον', 'I said, I spoke, 2 aor. → λέγω, φημί']
,['ἀγαθός –ή –όν', 'good, virtuous, brave, noble']
,['γε', '(enclitic) indeed; at least, at any rate']
,['δή', 'surely, really, now, in fact, indeed (gives greater exactness)']
,['πόλις πόλεως, ἡ', 'city, city-state']
,['εἷς μία ἕν', 'one']
,['ἵημι, ἥσω, ἧκα, -εἷκα, εἷμαι, -εἵθην', 'put in motion, let go, shoot; (mid.) hasten, rush']
,['δέω, δεήσω, ἐδέησα, δεδέηκα, δεδέημαι, ἐδεήθην', 'lack, miss, stand in need of (+gen.)']
,['ἄνθρωπος –ου, ὁ/ἡ', 'human being']
,['ὁράω, ὄψομαι, 2 aor. εἶδον, ἑόρακα and ἑώρακα, ὤφθην, impf. ἑώρων', 'see, look (to)']
,['μόνος μόνη μόνον', 'alone, single']
,['οὔτε...οὔτε', 'neither...nor']
,['οἷος οἵα οἷον', 'such as, of what sort, like, (exclam.) what a!, how! ; οἷός τε (+infin.) fit or able to; οἷόν τε (+infin.) it is possible to']
,['λαμβάνω, λήψομαι, ἔλαβον, εἴληφα, εἴλημμαι, ἐλήφθην', 'take, grasp, seize; receive, get']
,['δοκέω, δόξω, ἔδοξα', 'think, suppose, imagine (+acc. and infin.); seem, seem good; (impers.) δοκεῖ μοι it seems to me']
,['ἕτερος ἑτέρα ἕτερον', 'the other (of two); other, another']
,['κακός –ή –όν', 'bad, wicked, cowardly']
,['ἀνήρ ἀνδρός, ὁ', 'man, husband']
,['ἐπεί', 'after, since, when']
,['ὅσος ὅση ὅσον', 'however much; as great as; (in pl.) as many as; ὅσον (adv.) as much as']
,['καλέω, καλῶ, ἐκάλεσα, κέκληκα, κέκλημαι, ἐκλήθην', 'call, summon']
,['σῶμα σώματος, τό', 'body']
,['δεῖ, δεήσει, impf. ἔδει', 'it is necessary, one must, one ought (+acc. and infin.)']
,['ὥσπερ', 'just as, as if']
,['δίδωμι, δώσω, ἔδωκα, δέδωκα, δέδομαι, ἐδόθην', 'give, grant, offer']
,['ἔτι', 'still, yet']
,['φύσις φύσεως, ἡ', 'nature; (of the mind) one’s nature or disposition; regular order of nature']
,['μικρός –ά –όν', 'small, little, short']
,['δύναμαι, δυνήσομαι, ἐδυνήθην, δεδύνημαι', '(+infin.) to be able (to), be strong enough (to)']
,['ὥστε', '(introducing natural or actual result clause) so as, so that, (with the result) that']
,['ἀρχή ἀρχῆς, ἡ', 'beginning, origin; rule, empire, realm; magistracy']
,['ἕκαστος ἑκάστη ἕκαστον', 'each (of several)']
,['ἡμέρα ἡμέρας, ἡ', 'day']
,['φύω, φύσω, ἔφυσα', 'bring forth, produce, beget; 2 aor. ἔφυν grew, pf. πέφυκα be by nature']
,['ἅπας ἅπασα ἅπαν', 'all together']
,['ὅμοιος ὁμοία ὅμοιον', 'like, resembling (+dat.)']
,['νῦν, νυνί', 'now']
,['γῆ γῆς, ἡ', 'earth']
,['δύναμις δυνάμεως, ἡ', 'power, strength, ability']
,['καλός –ή –όν', 'beautiful, noble, honorable']
,['κύριος κυρίου, ὁ', 'lord, master']
,['μᾶλλον', 'more, rather; μᾶλλον...ἤ rather than']
,['ὅδε ἥδε τόδε', 'this']
,['ὅλος ὅλη ὅλον', 'whole, entire, complete']
,['μέρος μέρους, τό', 'part, share']
,['ἄρα', 'therefore, then (drawing an inference)']
,['ἐμός ἐμή ἐμόν', 'my, mine']
,['χράομαι, χρήσομαι, ἐχρησάμην, κέχρημαι, ἐχρήσθην', 'use, experience, suffer (+dat.); treat someone in a certain way (+dat. and adv.)']
,['δύο', 'two']
,['χρόνος χρόνου, ὁ', 'time']
,['ἴσος ἴση ἴσον', 'equal, the same as (+dat.)']
,['ὅταν (ὅτε-ἄν)', 'whenever (+subj.)']
,['μόνον', 'only']
,['οἶδα, infin. εἰδέναι, imper. ἴσθι, plupf. used as impf. ᾔδειν', 'to know (pf. in pres. sense); to know how to (+infin.)']
,['βασιλεύς βασιλέως, ὁ', 'king']
,['ὦ', 'oh! (unemphatic when with the vocative)']
,['βούλομαι, βουλήσομαι, βεβούλημαι, ἐβουλήθην', '(+infin.) will, wish (to); be willing (to); ὁ βουλόμενος anyone who likes']
,['φαίνω, φανῶ, ἔφηνα, πέφηνα, πέφασμαι, ἐφάνην', 'bring to light, make appear, make clear; (pass.) come to light, be seen, appear, appear to be (+ptc. or infin.)']
,['γράφω, γράψω, ἔγραψα, γέγραφα, γέγραμμαι, ἐγράφην', 'write']
,['φέρω, οἴσω, 1 aor. ἤνεγκα, 2 aor. ἤνεγκον, ἐνήνοχα, ἐνήνεγμαι, ἠνέχθην', 'carry, bring, fetch; carry off or away; φέρε come now, well']
,['ψυχή ψυχῆς, ἡ', 'breath, life, soul']
,['μηδείς μηδεμία μηδέν', 'no one, nothing']
,['αἴτιος αἰτία αἴτιον', 'responsible, guilty']
,['πάλιν', 'back, backwards; again']
,['μάλιστα', 'most, most of all; (in replies) certainly']
,['ὑπάρχω, ὑπάρξω, ὑπῆρξα, ὑπῆργμαι, ὑπήρχθην', 'exist, be, belong to; τὰ ὑπάρχοντα existing circumstances']
,['ἄρχω, ἄρξω, ἦρξα, ἦργμαι, ἤρχθην', 'begin (+gen.); lead, rule, govern (+gen.)']
,['γυνή γυναικός, ἡ', 'woman, wife']
,['ποτε (enclitic)', 'at some time, ever, in the world']
,['ἵνα', 'in order that (conj. +subj. or opt.); where (rel. adv. +indic.)']
,['ὄνομα ὀνόματος, τό', 'name; fame']
,['ὑπέρ', 'for (+gen), beyond (+acc.)']
,['ἤδη', 'already, now (of the immediate past); presently (of the immediate future)']
,['πατήρ πατρός, ὁ', 'father']
,['ἀκούω, ἀκούσομαι, ἤκουσα, ἀκήκοα, plup. ἠκηκόη or ἀκηκόη, ἠκούσθην', 'listen (to), hear (of)']
,['γένος γένους, τό', 'race, family; kind, class']
,['τόπος τόπου, ὁ', 'place; topic']
,['πράσσω, πράξω, ἔπραξα, πέπραχα, πέπραγμαι, ἐπράχθην', 'do, achieve, accomplish; do or fare in a certain way (+adv.)']
,['πρῶτος πρώτη πρῶτον', 'first, foremost, earliest; (adv.) τὸ πρῶτον in the first place']
,['εὑρίσκω, εὑρήσω, 2 aor. ηὗρον or εὗρον, ηὕρηκα or εὕρηκα, εὕρημαι, εὑρέθην', 'find (out), discover, devise']
,['παῖς παιδός, ὁ/ἡ', 'son, daughter, child; slave']
,['ἔρχομαι, fut. εἶμι or ἐλεύσομαι, 2 aor. ἦλθον, ἐλήλυθα', 'come, go']
,['υἱός υἱοῦ, ὁ', 'son']
,['ὕδωρ ὕδατος, τό', 'water']
,['ἴδιος ἰδία ἴδιον', 'one’s own; peculiar, separate, distinct']
,['σός σή σόν', 'your, yours (sg.; ὑμέτερος = pl.)']
,['γιγνώσκω, γνώσομαι, ἔγνων, ἔγνωκα, ἔγνωσμαι, ἐγνώσθην', 'come to know, learn; judge, think, or determine that (+acc. and infin.)']
,['τυγχάνω, τεύξομαι, ἔτυχον, τετύχηκα. τέτυγμαι, ἐτύχθην', 'hit, light upon, meet by chance (+gen.); reach, gain, obtain; happen to be (+ptc.)']
,['ἵστημι στήσω will set, ἔστησα set, caused to stand, 2 aor. ἔστην stood, ἕστηκα stand, plup. εἱστήκη stood, ἐστάθην stood', 'make to stand, set']
,['ἅμα', 'at the same time; (prep.) together with (+dat.)']
,['ἄγω, ἄξω, ἤγαγον, ἦχα, ἦγμαι, ἤχθην', 'lead, carry, bring; pass (time)']
,['τρόπος τρόπου, ὁ', 'way, manner, fashion; way of life, habit, custom']
,['μήτε...μήτε', 'neither...nor']
,['μέσος μέση μέσον', 'middle, in the middle, moderate; τὸ μέσον midst']
,['ἀλλήλων –οις', '(oblique cases plural only) one another, each other']
,['ἀεί', 'always']
,['φίλος φίλη φίλον', 'beloved, dear; friendly']
,['συμβαίνω, συμβήσομαι, 2 aor. συνέβην, συμβέβηκα', 'meet, come to an agreement, correspond; happen, occur, come to pass; turn out in a certain way (+adv.), result']
,['ἔργον ἔργου, τό', 'work, achievement, exploit']
,['πλέω, πλεύσομαι, ἔπλευσα, πέπλευκα, πέπλευσμαι, ἐπλεύσθην', 'sail']
,['τότε', 'then, at that time; οἱ τότε the men of that time (opp. οἱ νῦν)']
,['μήν', '[emphasizes preceding particle]']
,['χρή, impf. χρῆν or ἐχρῆν, infin. χρῆναι', 'it is necessary, it is fated, one ought (+infin. or +acc. and infin.)']
,['δείκνυμι, δείξω, ἔδειξα, δέδειχα, δέδειγμαι, ἐδείχθην', 'show, point out']
,['ζῷον ζῴου, τό', 'living being, animal']
,['πρᾶγμα πράγματος, τό', 'thing; (pl.) circumstances, affairs, business']
,['ἐναντίος ἐναντία ἐναντίον', 'opposite, facing; opposing']
,['τίθημι, θήσω, ἔθηκα, τέθηκα, τέθειμαι (but usu. κεῖμαι instead), ἐτέθην', 'to put, place; establish, ordain, institute; put in a certain state']
,['εἶδον, 2 aor. of ὁράω, act. infin. ἰδεῖν, mid.infin. ἰδέσθαι', 'I saw']
,['χείρ χειρός, ἡ', 'hand']
,['μηδέ', 'and not']
,['ὀλίγος ὀλίγη ὀλίγον', 'little, small, few']
,['νόμος νόμου, ὁ', 'custom, tradition, law']
,['κοινός –ή –όν', 'common, shared, mutual']
,['οἴομαι or οἶμαι, οἰήσομαι, impf. ᾤμην, aor. ᾠήθην', 'think, suppose, imagine (+acc. and infin.)']
,['κινέω, κινήσω, ἐκίνησα, κεκίνηκα, κεκίνημαι, ἐκινήθην', 'set in motion, move, rouse']
,['πάσχω, πείσομαι, ἔπαθον, πέπονθα', 'suffer, experience, be affected in a certain way (+adv.)']
,['πῶς', 'how?']
,['ὅσπερ ἥπερ ὅπερ', 'the very one who, the very thing which']
,['τοσοῦτος –αύτη –οῦτο(ν)', 'so large, so much']
,['σύν', 'with (+ dat. of accompaniment or means)']
,['εἶτα', 'then, next']
,['ἀληθής –ές', 'true']
,['δίκαιος δικαία δίκαιον', 'right, just']
,['μέλλω, μελλήσω, ἐμέλλησα', '(+infin.) think of doing, intend to, be about to']
,['ἐθέλω, ἐθελήσω, ἠθέλησα, ἠθέληκα', '(+infin.) wish (to); be willing (to)']
,['λοιπός –ή –όν', 'rest, remaining, rest-of-the']
,['ἀνάγκη ἀνάγκης, ἡ', 'necessity']
,['ὅτε', 'when, whenever (+indic. or opt.)']
,['δεύτερος –α –ον', 'second']
,['πόλεμος πολέμου ὁ', 'war']
,['χώρα χώρας, ἡ', 'land; place']
,['ζάω, ζήσω, ἔζησα, ἔζηκα', 'live']
,['πλῆθος πλήθους, τό', 'mass, throng, crowd; number']
,['ἥλιος ἡλίου, ὁ', 'sun']
,['αἰτία αἰτίας, ἡ', 'cause, origin; charge, accusation']
,['πείθω, πείσω, ἔπεισα, πέποιθα, πέπεισμαι, ἐπείσθην', 'persuade, win over; (mid. and pass.) obey, believe in, trust in (+dat.)']
,['πάρειμι', 'be present, be ready or at hand; (impers.) πάρεστί μοι it depends on me, it is in my power; τὰ παρόντα the present circumstances; τὸ παρόν just now']
,['πλεῖστος πλείστη πλεῖστον', 'most, greatest, largest (superl. of πολύς)']
,['εἶδος εἴδους, τό', 'form, shape, figure; class, kind, sort']
,['ὅπως', 'how, as; so that, in order that (+subj. or opt.)']
,['τρεῖς τρία', 'three']
,['βίος βίου, ὁ', 'life']
,['νομίζω, νομιῶ, ἐνόμισα, νενόμικα, νενόμισμαι, ἐνομίσθην', 'think, believe that (+acc. and infin.); hold as a custom, be accustomed to (+infin.)']
,['κύκλος κύκλου, ὁ', 'circle, ring, orb, disc, circular motion']
,['πάθος πάθους, τό', 'incident, accident, misfortune, experience; passion, emotion; state, condition']
,['πρό', 'before, in front of (+gen.)']
,['ὀνομάζω, ὀνομάσω, ὠνόμασα, ὠνόμακα, ὠνόμασμαι, ὠνομάσθην', 'call by name']
,['μέντοι', 'however; of course']
,['ἀρετή ἀρετῆς, ἡ', 'goodness, excellence; virtue; valor, bravery']
,['ὑμέτερος ὑμετέρα ὑμέτερον', 'your, yours (pl.; σός = sg.)']
,['ἔτος ἔτους, τό', 'year']
,['ἀντί', 'opposite (+gen.)']
,['ναῦς νεώς, ἡ', 'ship']
,['τρίτος –η –ον', 'third']
,['πνεῦμα πνεύματος, τό', 'wind, breath, spirit']
,['ὀρθός –ή –όν', 'upright, straight, true, regular']
,['θάλασσα θαλάσσης, ἡ', 'the sea']
,['διαφέρω, διοίσω, 1 aor. διήνεγκα, 2 aor. διήνεγκον, διενήνοχα, διενήνεγμαι', 'carry in different ways, spread; differ; (impers.) διαφέρει it makes a difference to (+dat.)']
,['μέχρι (+gen.)', 'until; (prep.) as far as, up to (+gen.)']
,['δόξα δόξης, ἡ', 'opinion, judgment; reputation, honor, glory']
,['κεφαλή –ῆς, ἡ', 'head']
,['πῦρ πυρός, τό', 'fire']
,['ἐλάσσων ἔλασσον', 'smaller, less, fewer (comp. of μικρός)']
,['πούς ποδός, ὁ', 'foot']
,['ἱερός –ά –όν', 'holy, venerated, divine']
,['εὐθύς εὐθεῖα εὐθύ', 'straight, direct; (adv.) immediately']
,['εἶμι, infin. ἰέναι, ptc. ἰών, ἰοῦσα, ἰόν', 'I will go (fut. of ἔρχομαι)']
,['ταχύς ταχεῖα ταχύ', 'quick, fast; (adv.) τάχα quickly; perhaps']
,['ποταμός –οῦ, ὁ', 'river, stream']
,['οὐσία οὐσίας, ἡ', 'substance, property; essence']
,['ἀριθμός –οῦ, ὁ', 'number']
,['ὕστερος ὑστέρα ὕστερον', 'coming after, following (+gen.); next, later; (adv.) ὕστερον afterwards']
,['φυλάσσω, φυλάξω, ἐφύλαξα, πεφύλαχα, πεφύλαγμαι, ἐφυλάχθην', 'watch, guard, defend; (mid.) be on one’s guard against (+acc.)']
,['καιρός καιροῦ, ὁ', 'the right time']
,['οἰκέω, οἰκήσω, ᾤκησα, ᾤκηκα, ᾠκήθην', 'inhabit, occupy']
,['ἀμφότερος ἀμφοτέρα ἀμφότερον', 'both']
,['σημεῖον σημείου, τό', 'sign, signal, mark']
,['παρέχω, παρέξω, παρέσχον, παρέσχηκα, impf. παρεῖχον', 'provide, present, offer; allow, grant']
,['ἑκάτερος ἑκατέρα ἑκάτερον', 'each (of two)']
,['δηλόω, δηλώσω, ἐδήλωσα, δεδήλωκα, ἐδηλώθην', 'show, declare, explain']
,['οἰκεῖος οἰκεία οἰκεῖον', 'domestic, of the house; one’s own; fitting, suitable']
,['κελεύω, κελεύσω, ἐκέλευσα, κεκέλευκα, κεκέλευσμαι, ἐκελεύσθην', 'order, bid, command (+acc. and infin.)']
,['τέλος τέλους, τό', 'end, fulfillment, achievement']
,['ἡγέομαι, ἡγήσομαι, ἡγησάμην, ἥγημαι', 'lead, be the leader; regard, believe, think']
,['ἄξιος ἀξία ἄξιον', 'worthy, deserving']
,['ἦ', 'truly (emphasizes what follows)']
,['δῆλος δήλη δῆλον', 'visible, clear, manifest']
,['τοίνυν (τοί-νυν)', 'therefore, accordingly (inferential); further, moreover (transitional)']
,['πολέμιος πολεμία πολέμιον', 'hostile; οἱ πολέμιοι the enemy']
,['ἔρομαι, ἐρήσομαι, 2 aor. ἠρόμην', 'ask, ask one about (+double acc.)']
,['ἀδελφός –οῦ, ὁ', 'brother']
,['μέγεθος μεγέθους, τό', 'greatness, size, magnitude']
,['εἴτε…εἴτε', 'whether…or']
,['κεῖμαι, κείσομαι', 'to lie, be situated, be laid up in store, be set up, be established or ordained (used as pf. pass. of τίθημι)']
,['πολλάκις', 'often']
,['πίνω, πίομαι, 2 aor. ἔπιον, πέπωκα, -πέπομαι, -επόθην', 'drink']
,['χάρις χάριτος, ἡ', 'splendor, honor, glory; favor, goodwill, gratitude, thanks']
,['ἔπειτα', 'then, next']
,['ζητέω, ζητήσω, ἐζήτησα, ἐζήτηκα', 'seek']
,['σχῆμα σχήματος, τό', 'form, figure, appearance, character']
,['τροφή τροφῆς, ἡ', 'nourishment, food']
,['μανθάνω, μαθήσομαι, ἔμαθον, μεμάθηκα', 'learn, ascertain']
,['ἐνταῦθα', 'here, there']
,['φεύγω, φεύξομαι, ἔφυγον, πέφευγα', 'flee, run away, avoid, shun']
,['ἵππος ἵππου, ὁ', 'horse']
,['κόσμος κόσμου, ὁ', 'order; ornament, decoration, adornment; world, universe']
,['αἷμα αἵματος, τό', 'blood']
,['αἱρέω, αἱρήσω, 2 aor. εἷλον, ᾕρηκα, ᾕρημαι, ᾑρέθην', 'take, grasp, take by force; (mid.) choose']
,['προστίθημι, προσθήσω, προσέθηκα, προστέθηκα, προστέθειμαι (but commonly προσκεῖμαι instead), προσετέθην', 'add; (med.) join']
,['ἀξιόω, ἀξιώσω, ἠξίωσα, ἠξίωκα, ἠξίωμαι, ἠξιώθην', 'consider worthy; require, demand, ask, claim']
,['ἕως', 'until; while, so long as']
,['νέος νέα νέον', 'young, new, fresh']
,['ἔοικα, ptc. εἰκώς', 'be like, look like (+dat.); seem; befit']
,['κἄν (καὶ-ἄν)', 'even if (+subj.)']
,['καθίστημι, καταστήσω, κατέστησα, κατέστην, καθέστηκα, plupf. καθειστήκη, κατεστάθην', 'set down, establish; bring into a certain state, render']
,['τέχνη τέχνης, ἡ', 'art, skill, craft']
,['χρῆμα χρήματος, τό', 'thing, matter; (more commonly in pl.) goods or property, esp. money']
,['σῴζω, σώσω, ἔσωσα, σέσωκα, ἐσώθην', 'save']
,['πέμπω, πέμψω, ἔπεμψα, πέπομφα, πέπεμμαι, ἐπέμφθην', 'send']
,['φωνή φωνῆς, ἡ', 'sound, voice']
,['ἕνεκα', 'on account of, for the sake of (+gen.)']
,['ἀπόλλυμι, ἀπολῶ, ἀπώλεσα, 2 aor. mid. ἀπωλόμην, pf. ἀπολώλεκα (“I have utterly destroyed”) or ἀπόλωλα (“I am undone”)', 'kill, destroy; (mid.) perish, die']
,['θάνατος θανάτου, ὁ', 'death']
,['νύξ νυκτός, ἡ', 'night']
,['ὁδός ὁδοῦ, ἡ', 'road, way, path']
,['ἔθνος ἔθνους, τό', 'nation']
,['ἀποδίδωμι, ἀποδώσω, ἀπέδωκα, ἀποδέδωκα, ἀποδέδομαι, ἀπεδόθην', 'give back; render; allow; (mid.) sell']
,['νοῦς (νόος), νοῦ (νόου), ὁ', 'mind, perception, sense']
,['μένω, μενῶ, ἔμεινα, μεμένηκα', 'stay, remain, endure, await']
,['ἀποθνῄσκω, ἀποθανοῦμαι, 2 aor. ἀπέθανον, ἀποτέθνηκα', 'die']
,['πάνυ', 'altogether, entirely']
,['εὖ', 'well (opp. κακῶς); thoroughly, competently; happily, fortunately']
,['κρίνω, κρινῶ, ἔκρινα, κέκρικα, κέκριμαι, ἐκρίθην', 'judge, decide, determine']
,['ἀναιρέω, ἀναιρήσω, ἀνεῖλον, ἀνῄρηκα, ἀνῄρημαι, ἀνῃρέθην', 'raise, take up; kill, destroy']
,['μακρός –ά –όν', 'long, tall, large, long-lasting']
,['ἥκω, ἥξω, pf. ἧκα', 'I have come, I am present']
,['ἡδονή –ῆς, ἡ', 'pleasure, enjoyment']
,['μήτηρ μητρός, ἡ', 'mother']
,['δεινός –ή –όν', 'awesome, terrible; clever, clever at (+infin.)']
,['διαφορά –ᾶς, ἡ', 'difference, disagreement']
,['κρατέω, κρατήσω, ἐκράτησα, κεκράτηκα, κεκράτημαι, ἐκρατήθην', 'be victorious, conquer, rule, surpass, excel (+gen.)']
,['δῆμος δήμου, ὁ', 'the (common) people; country district (opp. πόλις)']
,['οὐρανός –οῦ, ὁ', 'sky, heaven']
,['ἕπομαι ἕψομαι, 2 aor. ἑσπόμην', 'follow']
,['ἥσσων ἧσσον', 'less, weaker (comp. of κακός or μικρός)']
,['ὄρος ὄρους, τό', 'mountain, hill']
,['πλήν', '(prep.) except (+gen.); (conj.) except that, unless, but']
,['τέτταρες τέτταρα', 'four']
,['δυνατός –ή –όν', 'strong, powerful, able']
,['οἶκος οἴκου, ὁ', 'house, home, family']
,['ἄριστος ἀρίστη ἄριστον', 'best, noblest (superl. of ἀγαθός)']
,['ῥᾴδιος ῥᾳδία ῥᾴδιον', 'easy']
,['ἀφαιρέω, ἀφαιρήσω, ἀφεῖλον, ἀφῄρηκα, ἀφῄρημαι, ἀφῃρέθην', 'take from, take away']
,['τύχη τύχης, ἡ', 'luck, fortune (good or bad), fate, chance']
,['φανερός –ά –όν', 'clear, evident']
,['πρόσωπον προσώπου, τό', 'face, mask, person']
,['πιστεύω, πιστεύσω, ἐπίστευσα, πεπίστευκα, πεπίστευμαι, ἐπιστεύθην', 'trust, rely on, believe in (+dat.)']
,['διδάσκω, διδάξω, ἐδίδαξα, δεδίδαχα, δεδίδαγμαι, ἐδιδάχθην', 'teach']
,['ἄνω', 'up, upwards']
,['τάσσω, τάξω, ἔταξα, τέταχα, τέταγμαι, ἐτάχθην', 'arrange, put in order']
,['ὀφθαλμός –οῦ, ὁ', 'eye']
,['δέχομαι, δέξομαι, ἐδεξάμην, δέδεγμαι, -εδέχθην', 'take, accept; welcome, entertain']
,['ἀφικνέομαι, ἀφίξομαι, 2 aor. ἀφικόμην, ἀφῖγμαι', 'come to, arrive at']
,['ἱκανός –ή –όν', 'sufficient, enough; competent, able to (+infin.)']
,['ἐργάζομαι, ἐργάσομαι, εἰργασάμην, εἴργασμαι', 'work, labor']
,['μάχη μάχης, ἡ', 'battle']
,['τρέφω, θρέψω, ἔθρεψα, τέθραμμαι, ἐτράφην', 'nourish, feed, support, maintain; rear, educate']
,['ἀδύνατος –ον', 'impossible; powerless']
,['ἀκριβής –ές', 'exact, accurate, precise']
,['που', '(enclitic) somewhere; I suppose, perhaps (to qualify an assertion)']
,['ὅθεν', 'from where, whence']
,['στόμα στόματος, τό', 'mouth, face, opening']
,['χωρίς', 'separately, apart; (+gen.) without, separate from']
,['κρείσσων κρεῖσσον', 'stronger, mightier; better, more excellent (comp. of ἀγαθός)']
,['βραχύς βραχεῖα βραχύ', 'brief, short']
,['ἰσχυρός –ά –όν', 'strong']
,['ἀλήθεια ἀληθείας, ἡ', 'truth']
,['δίκη δίκης, ἡ', 'justice, lawsuit, trial, penalty']
,['χωρίον χωρίου, τό', 'place, spot, district']
,['ἡδύς ἡδεῖα ἡδύ', 'sweet, pleasant']
,['νόσος νόσου, ὁ', 'disease, sickness']
,['λίθος λίθου, ὁ', 'stone']
,['παλαιός –ά –όν', 'old, ancient']
,['ἀφίημι, ἀφήσω, ἀφῆκα, ἀφεῖκα, ἀφεῖμαι, ἀφείθην', 'send away, let go; let alone, neglect']
,['ἄλλως', 'otherwise']
,['πρᾶξις πράξεως, ἡ', 'action, transaction, business']
,['σαφής σαφές', 'clear, distinct, plain']
,['σοφός –ή –όν', 'wise, clever, skilled']
,['νικάω, νικήσω, ἐνίκησα, νενίκηκα, νενίκημαι, ἐνικήθην', 'conquer, win']
,['ὁμολογέω, ὁμολογήσω, ὡμολόγησα, ὡμολόγηκα, ὡμολόγημαι, ὡμολογήθην', 'agree with, say the same thing as (+dat.)']
,['ναός (νεώς) ναοῦ (νεώ), ὁ', 'temple']
,['αὖ, αὖθις', 'moreover; on the other hand; back (again)']
,['πατρίς πατρίδος, ἡ', 'fatherland']
,['ὀξύς ὀξεῖα ὀξύ', 'sharp, keen, shrill, pungent']
,['καίτοι (καί-τοι)', 'and indeed, and yet']
,['πλέον', 'more, rather']
,['πλέων πλέον', 'more, larger (comp. of πολύς)']
,['γνώμη γνώμης, ἡ', 'thought, intelligence, opinion, purpose']
,['τιμή τιμῆς, ἡ', 'honor, esteem; price, value; office, magistracy']
,['μεταξύ', 'between']
,['προσήκω προσήξω', 'belong to, have to do with; be fitting for (+dat.); arrive at; οἱ προσήκοντες relatives; τὰ προσήκoντα duties']
,['πρίν', 'before, until']
,['ἀδικέω, ἀδικήσω, ἠδίκησα, ἠδίκηκα, ἠδίκημαι, ἠδικήθην', 'do wrong; injure']
,['στρατηγός –οῦ, ὁ', 'leader of an army, commander, general']
,['οὐκέτι', 'no longer, no more']
,['πρέσβυς πρέσβεως, ὁ', 'old man; (pl.) ambassadors']
,['παύω, παύσω, ἔπαυσα, πέπαυκα, πέπαυμαι, ἐπαύθην', 'stop, put an end to; (mid.) cease']
,['τελευτάω, τελευτήσω, ἐτελεύτησα, τετελεύτηκα, τετελεύτημαι, ἐτελευτήθην', 'finish; die']
,['μίγνυμι, μείξω, ἔμειξα, μέμειγμαι, ἐμείχθην', 'mix, mingle']
,['λαός λαοῦ, ὁ', 'the people, folk']
,['θυγάτηρ θυγατρός, ἡ', 'daughter']
,['οἰκία οἰκίας, ἡ', 'building, house, dwelling']
,['παραδίδωμι, παραδώσω, παρέδωκα, παραδέδωκα, παραδέδομαι, παρεδόθην', 'transmit, hand over, surrender']
,['ἔξω', 'outside; except']
,['νῆσος νήσου, ἡ', 'island']
,['ἐκεῖ', 'there']
,['ἐπιστήμη –ης, ἡ', 'knowledge, understanding, skill']
,['ἐάω, ἐάσω, εἴασα', 'allow, permit (+acc. and infin.); let be, let alone']
,['θαυμάζω, θαυμάσομαι, ἐθαύμασα, τεθαύμακα, τεθαύμασμαι, ἐθαυμάσθην', 'to be in awe (of), be astonished (at)']
,['αἰσθάνομαι, αἰσθήσομαι, 2 aor. ᾐσθόμην, ᾔσθημαι', 'perceive, understand, hear, learn']
,['χαίρω, χαιρήσω, κεχάρηκα, κεχάρημαι, ἐχάρην', 'to be happy, rejoice at (+dat.), take joy in (+ptc.); χαῖρε, (pl.) χαίρετε hello, goodbye']
,['χαλεπός –ή –όν', 'difficult, troublesome']
,['τέκνον τέκνου, τό', 'child']
,['καταλαμβάνω, καταλήψομαι, κατέλαβον, κατείληφα, κατείλημμαι, κατελήφθην', 'seize, catch up with, arrest, compel']
,['μάχομαι, μαχοῦμαι, ἐμαχεσάμην, μεμάχημαι', 'fight (against) (+dat.)']
,['μιμνήσκω, -μνήσω, -έμνησα, pf. μέμνημαι, ἐμνήσθην', 'remind; (in pf. mid.) remember']
,['λύω, λύσω, ἔλυσα, λέλυκα, λέλυμαι, ἐλύθην', 'loosen, unbind, set free; undo, destroy']
,['θνῄσκω, 2 aor. -έθανον, τέθνηκα, θανοῦμαι', 'to die, be dying']
,['τιμάω, τιμήσω, ἐτίμησα, τετίμηκα, τετίμημαι, ἐτιμήθην', 'to honor']
,['τεῖχος τείχους, τό', 'wall']
,['ἴσως', 'equally, probably, perhaps']
,['αἴρω, ἀρῶ, ἦρα, ἦρκα, ἦρμαι, ἤρθην', 'take up, lift up; remove']
,['ἀποκτείνω, ἀποκτενῶ, ἀπέκτεινα, ἀπέκτονα', 'kill']
,['στρατιώτης –ου, ὁ', 'soldier']
,['ἄνευ', 'without (+gen.)']
,['πότερος ποτέρα πότερον', 'which of the two? πότερον whether']
,['ἁπλῶς', 'simply, singly, in one way']
,['πίπτω, πεσοῦμαι, ἔπεσον, πέπτωκα', 'fall, fall down']
,['τέταρτος –η –ον', 'fourth']
,['κατασκευάζω, κατασκευάσω, κατεσκεύασα', 'equip, furnish, make ready']
,['ἐχθρός –ά –όν', 'hated, hateful; hostile to (+dat.)']
,['ἀγών ἀγῶνος, ὁ', 'contest; struggle']
,['κωλύω, κωλύσω, ἐκώλυσα, κεκώλυκα, κεκώλυμαι, ἐκωλύθην', 'hinder, check, prevent (+acc. and infin.)']
,['ἁμαρτάνω, ἁμαρτήσομαι, ἡμάρτησα, 2 aor. ἥμαρτον, ἡμάρτηκα, ἡμάρτημαι, ἡμαρτήθην', 'miss the mark (+gen.); fail, be wrong, make a mistake']
,['διαφθείρω, διαφθερῶ, διέφθειρα, διέφθαρκα, διέφθαρμαι, διεφθάρην', 'destroy; corrupt']
,['πως', '(enclitic) somehow, in some way, in any way']
,['πόνος πόνου, ὁ', 'work, labor; stress, trouble, pain']
,['ἔνθα', 'there']
,['τάξις τάξεως, ἡ', 'arrangement, order; military unit']
,['πειράω (usually mid. πειράομαι), πειράσομαι, ἐπείρασα, πεπείραμαι, ἐπειράθην', 'attempt, try, make a trial of (+gen.)']
,['φοβέω, φοβήσω, ἐφόβησα, πεφόβημαι, ἐφοβήθην', 'put to flight; (mid. and pass.) flee, fear']
,['βάλλω, βαλῶ, 2 aor. ἔβαλον, βέβληκα, βέβλημαι, ἐβλήθην', 'throw, hurl; throw at, hit (acc.) with (dat.)']
,['πονηρός –ά –όν', 'worthless, bad, wicked']
,['ξένος ξένου, ὁ', 'guest-friend; foreigner, stranger']
,['βάρβαρος –ον', 'non-Greek, foreign; barbarous']
,['ὅπου', 'where, wherever']
,['συμφέρω, συνοίσω, 1 aor. συνήνεγκα', 'benefit, be useful or profitable to (+dat.); (impers.) συμφέρει it is of use, expedient (+infin.); τὸ συμφέρον use, profit, advantage']
,['πυνθάνομαι, πεύσομαι, 2 aor. ἐπυθόμην, πέπυσμαι', 'learn, hear, inquire concerning (+gen.)']
,['δοῦλος δούλου, ὁ', 'slave']
,['τέμνω, τεμῶ, 2 aor. ἔτεμον, -τέτμηκα, τέτμημαι, ἐτμήθην', 'cut, cut down, cut to pieces']
,['χρήσιμος χρησίμη χρήσιμον', 'useful, serviceable']
,['ποῖος ποία ποῖον', 'what sort of?']
,['ὅπλον ὅπλου, τό', 'weapon, tool, implement (mostly pl.)']
,['πίστις πίστεως, ἡ', 'trust in others, faith; that which gives confidence, assurance, pledge, guarantee']
,['ὑπολαμβάνω, ὑπολήψομαι, ὑπέλαβον, ὑπείληφα, ὑπείλημμαι, ὑπελήφθην', 'take up, seize; answer, reply; assume, suppose']
,['ποιητής –οῦ, ὁ', 'creator, poet']
,['λανθάνω, λήσω, ἔλαθον, λέληθα', 'escape the notice of (+acc. and nom. participle), be unknown; (mid. and pass.) forget']
,['βελτίων βέλτιον', 'better (comp. of ἀγαθός)']
,['πάντως', 'altogether, in all ways; at any rate']
,['πορεύω, πορεύσω, ἐπόρευσα, πεπόρευμαι, ἐπορεύθην', 'carry; (mid. and pass) go, walk, march']
,['ἀποκρίνω, ἀποκρινῶ, ἀπεκρινάμην, ἀπεκρίθη', 'separate, set apart, choοse; (mid.) answer, reply']
,['πέντε', 'five']
,['κίνδυνος κινδύνου, ὁ', 'danger']
,['κατηγορέω, κατηγορήσω, κατηγόρησα, κατηγόρηκα, κατηγόρημαι, κατηγορήθην', 'to speak against, to accuse (+gen.)']
,['τρέπω, τρέψω, ἔτρεψα, τέτροφα, ἐτράπην', 'turn, direct towards a thing; put to flight, defeat; (pass.) turn one’s steps in a certain direction, go']
,['ὅμως', 'nevertheless, all the same, notwithstanding']
,['θεῖος θεία θεῖον', 'divine']
,['ἱππεύς ἱππέως, ὁ', 'horseman, rider, charioteer']
,['κτάομαι, κτήσομαι, ἐκτησάμην, κέκτημαι', 'get, gain, acquire']
,['λείπω, λείψω, ἔλιπον, λέλοιπα, λέλειμμαι, ἐλείφθην', 'leave, abandon']
,['βουλή βουλῆς, ἡ', 'will, determination; counsel, piece of advice; council of elders']
,['ἐλπίς ἐλπίδος, ἡ', 'hope; expectation']
,['γραφή γραφῆς, ἡ', 'a drawing, painting, writing; indictment']
,['τίκτω, τέξω or τέξομαι, ἔτεκον, τέτοκα, τέτεγμαι, ἐτέχθην', 'beget, give birth to, produce']
,['κομίζω, κομιῶ, ἐκόμισα, κεκόμικα, κεκόμισμαι, ἐκομίσθην', 'take care of, provide for']
,['θυμός θυμοῦ, ὁ', 'life, spirit; soul, heart, mind']
,['βλέπω, βλέψομαι, ἔβλεψα', 'see, look (at)']
,['φόβος φόβου, ὁ', 'panic, fear, flight']
,['πολιτεία –ας, ἡ', 'constitution, citizenship, republic']
,['στάδιον σταδίου, τό (pl. στάδια and στάδιοι)', 'stadion or stade, the longest Greek unit of linear measure, about 185 meters']
,['φρονέω, φρονήσω, ἐφρόνησα', 'think, intend to (+infin.); be minded towards (+adv. and dat.)']
,['τοιόσδε τοιάδε τοιόνδε', 'such (as this), of such a sort (as this)']
,['ὁρμάω, ὁρμήσω, ὥρμησα, ὥρμηκα, ὥρμημαι, ὡρμήθην', 'set in motion, urge on; (intrans.) start, hasten on']
,['παρασκευάζω, παρασκευάσω, παρεσκεύασα', 'get ready, prepare, provide']
,['λαλέω, λαλήσω, ἐλάλησα, λελάληκα, ἐλαλήθην', 'talk, chatter, babble']
,['δράω, δράσω, ἔδρασα, δέδρακα, δέδραμαι, ἐδράσθην', 'do, accomplish']
,['σκοπέω, σκοπήσω, ἐσκόπησα', 'look at, watch; look into, consider, examine']
,['βοῦς βοός, ὁ/ἡ', 'bull, ox, cow']
,['ἡμέτερος ἡμετέρα ἡμέτρον', 'our']
,['γράμμα γράμματος, τό', 'letter, written character; (pl.) piece of writing, document(s)']
,['ἐρωτάω, ἐρήσομαι, 2 aor. ἠρόμην', 'ask someone (acc.) something (acc.); question, beg']
,['πολεμέω, πολεμήσω, ἐπολέμησα, πεπολέμηκα', 'make war']
,['θύω, θύσω, ἔθυσα, τέθυκα, τέθυμαι, ἐτύθην', 'sacrifice']
,['ἐλαύνω, ἐλῶ, ἤλασα, -ελήλακα, ἐλήλαμαι, ἠλάθην', 'drive, set in motion']
,['δέδοικα, δείσομαι, ἔδεισα', 'fear']
,['σύμμαχος –ον', 'allied with (+dat.); οἱ σύμμαχοι allies']
,['ἡγεμών ἡγεμόνος, ὁ', 'guide, leader, commander']
,['βαρύς βαρεῖα βαρύ', 'heavy, grievous, tiresome']
,['ὧδε', 'thus, in this way; hither, here']
,['αἰσχρός –ά –όν', 'ugly, shameful, disgraceful']
,['εἰρήνη εἰρήνης, ἡ', 'peace']
,['ἁλίσκομαι, ἁλώσομαι, 2 aor. ἑάλων, ἑάλωκα', 'to be taken, conquered (act. supplied by αἱρέω)']
,['δέκα', 'ten']
,['ἀμείνων ἄμεινον', 'better, abler, stronger, braver (comp. of ἀγαθός)']
,['χείρων χεῖρον', 'worse, inferior (comp. of κακός)']
,['βοηθέω, βοηθήσω, ἐβοήθησα, βεβοήθηκα', 'help, assist (+dat.)']
,['λαμπρός –ά –όν', 'bright, brilliant; well-known, illustrious']
,['ἀπαλλάσσω, ἀπαλλάξω, ἀπήλλαξα, ἀπήλλαχα, ἀπήλλαγμαι, ἀπηλλάχθην or ἀπηλλάγην', 'set free, release, deliver']
,['βουλεύω βουλεύσω, ἐβούλευσα, βεβούλευκα, βεβούλευμαι, ἐβουλεύθην', 'plan (to), decide (to); (mid.) deliberate']
,['μάλα', 'very, very much']
,['αἰτέω, αἰτήσω, ᾔτησα, ᾔτηκα, ᾔτημαι, ᾐτήθην', 'ask (for), beg']
,['σωτηρία σωτηρίας, ἡ', 'safety, deliverance']
,['ἆρα', '[introduces a question]']
,['διώκω, διώξομαι, ἐδίωξα, δεδίωχα, ἐδιώχθην', 'pursue']
,['δαίμων δαίμονος, ὁ/ἡ', 'spirit, god, demon']
,['οὐκοῦν', 'surely then (inviting assent to an inference)']
,['γλῶσσα γλώσσης, ἡ', 'tongue; language']
,['ἑπτά', 'seven']
,['τολμάω, τολμήσω, ἐτόλμησα, τετόλμηκα, τετόλμημαι, ἐτολμήθην', 'have the courage, dare; undertake, undergo']
,['δεσπότης –ου, ὁ', 'master (of the household); absolute ruler']
,['εἰκός εἰκότος, τό', 'likelihood, probability; εἰκός (ἐστι) it is likely (+infin.) →ἔοικα']
,['ἄδικος ἄδικον', 'unjust']
,['εἴκοσι(ν)', 'twenty']
,['μυρίος μυρία μυρίον', 'countless; μύριοι 10,000; μυριάς -άδος ἡ 10,000, a countless amount']
,['αὐτίκα', 'at once, immediately']
,['δέκατος –η –ον', 'tenth']
,['βαίνω, βήσομαι, 2 aor. ἔβην, βέβηκα', 'walk, come, go']
,['περ', '[enclitic added to pronouns and other particles for emphasis]']
,['ἐλεύθερος ἐλευθέρα ἐλεύθερον', 'free, independent']
,['στρατιά –ᾶς, ἡ', 'army']
,['ἀμφί', 'about, around']
,['συμφορά –ᾶς, ἡ', 'event, circumstance, misfortune']
,['ἑκατόν', 'hundred']
,['νίκη νίκης, ἡ', 'victory']
,['ἔπος ἔπους, τό', 'word, speech, tale; prophecy']
,['στρατός –οῦ, ὁ', 'army']
,['φράζω, φράσω, ἔφρασα, πέφρακα, πέφρασμαι, ἐφράσθην', 'tell, declare; (mid. and pass.) think (about)']
,['ἀργύριον ἀργυρίου, τό', 'money']
,['τριάκοντα', 'thirty']
,['ἕξ', 'six']
,['πεμπτός –ή –όν', 'fifth']
,['μάρτυς μάρτυρος, ὁ/ἡ', 'witness']
,['χαλκοῦς –ῆ –οῦν', 'of copper or bronze']
,['ἕβδομος –η –ον', 'seventh']
,['ποῦ', 'where']
,['ναί', 'indeed, yes (used in strong affirmation)']
,['φῶς φωτός, τό', 'light, daylight']
,['ὀκτώ', 'eight']
,['ἕκτος –η –ον', 'sixth']
,['τριακοστός –ή –όν', 'thirtieth']
,['ἐννέα', 'nine']
,['πότε', 'when?']
,['ὄγδοος –η –ον', 'eighth']
,['ἔνατος –α –ον', 'ninth']
,['εἰκοστός –ή –όν', 'twentieth']
,['ἀγγέλλω, ἀγγελῶ, ἤγγειλα, ἤγγελκα, ἤγγελμαι, ἠγγέλθην', 'report, tell']
,['ἑκατοστός –ή –όν', 'hundredth']

    ]